import React, { createContext, useState, useEffect } from 'react';

const translations = {
  en: {
    siteName: "Fusion Gene Portal",
    nav: { home: "Home", search: "Search", sniffer: "SNIFFER", login: "Login" },
    home: {
      loading: "Loading data...",
      uniqueFusions: "Unique Fusion Genes",
      uniqueGenes: "Genes Involved",
      sampleCount: "Samples",
      searchTitle: "🔍 Search Fusion Genes",
      searchPlaceholder: "Enter gene name or fusion name...",
      searchButton: "Search",
      searchTip: "",
      suggestionTypeGene: "Gene",
      suggestionTypeFusion: "Fusion",
      circosTitle: "🧬 Chromosome Fusion Circos Plot",
      circosSubtitle: "Select a chromosome to view its fusion genes",
      selectChromosome: "Select Chromosome",
      top100Title: "📊 High-Frequency Fusion Genes (Top 100)",
      top100Subtitle: "Sorted by Frequency (fq) descending",
      fqLabel: "Frequency (fq)",
      cellLineSampleCount: "Cell Line Samples",
      showingRange: (start, end, total) => `Showing ${start} – ${end} of ${total}`,
      todayHighlight: "⭐ Today's Fusion Gene",
      fusionName: "Fusion Name",
      leftGene: "Left Gene",
      rightGene: "Right Gene",
      frequency: "Frequency (fq)",
      viewDetails: "View Details →",
      snifferTitle: "🔬 About the SNIFFER Algorithm",
      snifferIntro: "SNIFFER is an advanced algorithm for detecting gene fusions from sequencing data. It automates the identification of fusion breakpoints and provides comprehensive visualization of gene fusion events, helping researchers prioritize biologically significant fusions for further analysis.",
      literatureTitle: "📚 Fusion Gene Literature from Prof. Meidan Ying's Group",
      literatureList: [
        { href: "https://pubmed.ncbi.nlm.nih.gov/?term=A%20novel%20gene%20fusion%20RUNX1/ZNF423%20promotes%20leukemic%20relapse%20of%20NUP98-rearranged%20AML", color: "blue", title: "A novel gene fusion RUNX1/ZNF423 promotes leukemic relapse of NUP98-rearranged AML", desc: "Study on RUNX1/ZNF423 fusion and leukemic relapse in NUP98-rearranged AML" },
        { href: "https://pubmed.ncbi.nlm.nih.gov/?term=Deneddylation%20of%20PML/RARa%20Reconstructs%20Functional%20PML%20Nuclear%20Bodies%20via%20Orchestrating%20Phase%20Separation%20to%20Eradicate%20APL", color: "purple", title: "Deneddylation of PML/RARa Reconstructs Functional PML Nuclear Bodies via Orchestrating Phase Separation to Eradicate APL", desc: "Mechanistic study on PML/RARa deneddylation, phase separation, and APL eradication" },
        { href: "https://pubmed.ncbi.nlm.nih.gov/42151502/", color: "green", title: "Targeting fusion proteins in solid tumors: from oncogenic mechanisms to clinical interventions", desc: "Acta Pharmacologica Sinica, 2026 - Prof. Meidan Ying group review on fusion proteins and therapeutic targeting in solid tumors" },
        { href: "https://pubmed.ncbi.nlm.nih.gov/39227737/", color: "orange", title: "Palmitoyltransferase ZDHHC3 is essential for the oncogenic activity of PML/RARa in acute promyelocytic leukemia", desc: "Acta Pharmacologica Sinica, 2025 - Mechanistic study involving the PML/RARa fusion protein in leukemia" }
      ],
      deletedTitle: "🚫 Low-Confidence Fusion Genes (Top 100)",
      deletedSubtitle: "Candidate fusions filtered out by SNIFFER · Sorted by Frequency (fq) descending",
      filterLabel: "Filter Type:",
      filterAll: "All (no filter)",
      filterClear: "Clear",
      currentFilter: "Current filter:",
      totalCount: (n) => `Total ${n}`,
      deletedLoading: "Loading low-confidence fusions...",
      noData: "No data available",
      noDataForFilter: "No fusion genes for this filter type",
      clickToFilter: (val) => `Click to filter: ${val}`,
      deletedShowingRange: (start, end, total) => `Showing ${start} – ${end} of ${total}`,
      // ── Cell Line & Disease filter (Home) ──
      targetBannerTitle: "SNIFFER Target Analysis",
      cellLineBannerTitle: "SNIFFER Cell Line Analysis",
      targetBannerSubtitle: "Fusion gene results detected by SNIFFER from pediatric TARGET AML sequencing data",
      cellLineBannerSubtitle: "Fusion gene results detected by SNIFFER from 1019 CCLE cell line samples",
      cellLineModuleSubtitle: "Data from SNIFFER processing of 1019 cell line samples in CCLE",
      diseaseTypesLabel: "Disease Types",
      cellLineSamplesLabel: "Cell Line Samples",
      tissueOriginsLabel: "Tissue Origins",
      filterByDiseaseType: "Filter by disease type",
      clearSelection: "Clear",
      selectAll: "Select all",
      deselectAll: "Deselect all",
      selectedDiseasesCount: (n) => `${n} disease(s) selected:`,
      pleaseSelectDisease: "Please select disease type(s) first",
      drawSelectedDiseases: (n) => `Top 20 fusions for ${n} selected disease(s)`,
      diseasesFilterDesc: (n) => `${n} disease(s)`,
      cellLineFilterDesc: (name) => `Cell line: ${name}`,
      clearFilter: "Clear filter",
      searchByCellLine: "Search by cell line",
      downloadCellLineData: (name) => `Download ${name} data (CSV)`,
      noFusionForFilter: "No fusion gene data for this filter",
      chartNoDataForFilter: "No data for this filter criteria",
      allDiseases: (n) => `All diseases (${n})`,
      allCellLines: (n) => `All cell lines (${n})`,
    },
    search: {
      pageTitle: "🔬 Fusion Gene Search",
      pageSubtitle: "Search, filter and visualize fusion gene data",
      modePass: "PASS",
      modeGlobal: "Global Search",
      modeLabelPass: "🧬 High-confidence Fusion Genes (PASS) · ID format: TP+number",
      modeLabelGlobal: "🌐 Search PASS database + FILTER data · ID format: TP+number / TF+number",
      placeholderPass: (idEnabled) => `Search gene name, fusion name or ID...`,
      placeholderGlobal: (idEnabled) => `Global search gene name, fusion name or ID...`,
      suggestionTypeGene: "Gene",
      suggestionTypeFusion: "Fusion",
      idSearchOn: "ID Search ON",
      idSearchOff: "ID Search OFF",
      idSearchTitleOn: (prefix) => `ID search enabled: ${prefix}+number for exact lookup`,
      idSearchTitleOff: "ID search disabled",
      searching: "Searching...",
      fuzzySearch: "🔍 Fuzzy Search",
      exactSearch: "🎯 Exact Search",
      hintExact: "🎯 Exact: only matches fusions where a gene name exactly equals the search term (e.g. RP2 only finds fusions with RP2 as one gene)",
      hintFuzzy: "🔍 Fuzzy: matches all fusions containing the keyword",
      idSearchEnabledHint: (prefix) => `· ID search on: ${prefix}+number for exact lookup`,
      idSearchDisabledHint: "· ID search disabled",
      advancedFilter: "🎯 Advanced Filter",
      advancedFilterActive: "(Active)",
      advancedHint: "💡 Use advanced filters alone or combine with the keyword search above",
      advancedSearchOnly: "🎯 Run Advanced Search Only",
      filterBy: "Filter by:",
      byChromosome: "🧬 By Chromosome",
      byGene: "🔬 By Gene",
      leftChromosome: "Left Chromosome",
      rightChromosome: "Right Chromosome",
      allChromosomes: "All Chromosomes",
      leftGeneLabel: "🔬 Left Gene",
      rightGeneLabel: "🔬 Right Gene",
      leftGenePlaceholder: "Enter left gene name...",
      rightGenePlaceholder: "Enter right gene name...",
      sortField: "Sort Field",
      sortOrder: "Sort Order",
      sortDesc: "Descending (High to Low)",
      sortAsc: "Ascending (Low to High)",
      combinedSearch: "Current combined search:",
      keywordBadge: (q) => `🔍 Keyword: ${q}`,
      leftChrBadge: (c) => `🧬 Left: ${c}`,
      rightChrBadge: (c) => `🧬 Right: ${c}`,
      leftGeneBadge: (g) => `🔬 Left gene: ${g}`,
      rightGeneBadge: (g) => `🔬 Right gene: ${g}`,
      andActive: "→ Both active",
      resultsTitle: (mode) => mode === 'pass' ? '✅ PASS Search Results' : '🌐 Global Search Results',
      totalFound: (n) => `Found ${n} fusion genes`,
      tableHeadersPass: ['ID', 'Fusion Name', 'Left Gene', 'Left Breakpoint', 'Right Gene', 'Right Breakpoint', 'Annots', 'Freq'],
      legendPass: "PASS data (Fusion DB)",
      legendFilter: "FILTER data (fusiondeleted)",
      legendExpand: "▶ Click row arrow to expand variants",
      variantsCount: (n) => `${n} other variants`,
      loadingVariants: "Loading variant data...",
      circosTitle: "🎨 Fusion Gene Circos Plot",
      circosGlobalTitle: "🎨 Global Search Circos Plot",
      circosGlobalSubtitle: "Includes PASS + FILTER data, sorted by fq",
      displayRange: "Display range:",
      junctionTitle: "📊 Junction & Spanning Reads",
      junctionGlobalTitle: "📊 Global Junction & Spanning Reads",
      junctionGlobalSubtitle: "Includes PASS + FILTER data, sorted by total count",
      showTop: "Show top:",
      itemsOfTotal: (n) => `items / total ${n}`,
      fusionsOfTotal: (n) => `fusions / total ${n}`,
      networkTitle: "🌐 Gene Fusion Network",
      networkGlobalTitle: "🌐 Global Fusion Network",
      networkGlobalSubtitle: "Includes PASS + FILTER data",
      showingRange: (start, end, total) => `Showing ${start} - ${end} of ${total}`,
      firstPage: "First",
      lastPage: "Last",
      noResultsTitle: "No matching results",
      noResultsHint: "Try adjusting your search conditions or use a different search method",
      initialTitlePass: "Start searching PASS fusion genes",
      initialTitleGlobal: "Start global fusion gene search",
      initialSubtitlePass: "High-confidence fusion gene database",
      initialSubtitleGlobal: "Search both PASS database + FILTER data, results displayed together",
      loadingPass: "Searching...",
      loadingGlobal: "Searching PASS + FILTER data...",
      descSearch: (q) => `Search: "${q}"`,
      descLeftChr: (c) => `Left Chr: ${c}`,
      descRightChr: (c) => `Right Chr: ${c}`,
      descLeftGene: (g) => `Left Gene: ${g}`,
      descRightGene: (g) => `Right Gene: ${g}`,
      // ── Cell Line DB (Search page) ──
      cfModeLabelCellLine: "🧫 Cell Line DB — Search CCLE cell line fusion gene database",
      cfSearchPlaceholder: "Search fusion gene name or CL ID (e.g. YWHAE--CRK, CL18)",
      cfCellLinePlaceholder: "Cell line (e.g. MCF7)",
      cfSearching: "Searching",
      cfSearchBtn: "Search",
      cfSearchHint: "Based on 1019 CCLE cell line samples · Fuzzy matching for fusion name / cell line",
      cfResultsSummary: (records, fusions) => `${records} records · ${fusions} fusion genes`,
      cfDiseaseFilterToggle: "🏥 Disease Type Filter",
      cfDiseasesSelected: (n) => `${n} selected`,
      cfSearchingLoading: "Searching Cell Line database...",
      cfNoResults: "No matching fusion genes found",
      cfNoResultsHint: "Please try different search criteria",
      cfInitialHint: "Enter fusion gene name, CL ID, cell line name or disease type to search",
      cfInitialHint2: "Supports three conditions individually or combined · Supports exact matching of disease names with commas in parentheses",
      cfResultsTitle: "🧫 Cell Line DB Search Results",
      cfResultsCount: (fusions, records) => `${fusions} fusion genes · ${records} cell line records`,
      cfSearchContentLabel: (q) => `Search: ${q}`,
      cfDiseasesFiltered: (n) => `${n} diseases filtered`,
      cfExpandable: "Expandable (multiple cell line samples)",
      cfClickHint: "Click fusion name → detail page (PASS data preferred, otherwise Cell Line detail)",
      cfFusionClickTitle: "Go to fusion detail page (PASS database preferred, otherwise Cell Line detail)",
      cfVariantCount: (n) => `${n} cell line samples`,
      cfShowingRange: (start, end, total) => `Showing ${start}–${end} / ${total} fusions`,
      cfFilterByDiseaseType: "Filter by disease type",
      cfClearSelection: "Clear",
      cfSelectAll: "Select all",
      cfDeselectAll: "Deselect all",
      cfSelectedDiseasesCount: (n) => `${n} disease(s) selected:`,
      cfPleaseSelectDisease: "Please select disease type(s) first",
      cfFilterSelectedDiseases: (n) => `Filter ${n} selected disease(s)`,
      cfAllCellLines: (n) => `All cell lines (${n})`,
      cfAllDiseases: (n) => `All diseases (${n})`,
      cfAllTissues: (n) => `All tissues (${n})`,
    },
    sniffer: {
      title: "SNIFFER Analysis",
      hint: "Upload a fusion CSV file for on-the-fly analysis (data will not be saved):",
      button: "Run Analysis",
      summary: (total, genes, chrs) => `Found **${total}** fusions involving **${genes}** unique genes across **${chrs}** chromosomes.`,
      chartTitle: "Circos Plot for Uploaded Data",
      failure: "Analysis failed, please check file format.",
      loginRequired: "Please login to use the SNIFFER algorithm service.",
      loginButton: "Go to Login"
    },
    circos: {
      tooltipChr: (name, count) => `Click to filter ${name} (${count} fusions in current results)`,
      tooltipFusion: (name, fq, ffpm) => `${name} | fq: ${fq} | FFPM: ${ffpm} | Click to view details`,
      legendTitle: "Fusion Gene Circos Plot",
      legendSubtitle: (n) => `Showing ${n} fusions (sorted by fq descending)`,
      legendTip: "💡 Click chromosome arc to add filter | Click link to view fusion details | Line width indicates frequency",
    },
    junction: {
      tooltipClickDetail: "Click to view details",
      noData: "No data available",
      hint: "💡 <strong>Tip:</strong> Chart uses log₂ scale for better visualization; labels show raw counts. Blue bars = Junction Reads, green bars = Spanning Fragments.",
      hintClick: "Click a fusion name or bar to view details.",
    },
    network: {
      noData: "No data available",
      tooltipTotalFq: "Total fq",
      tooltipConnections: "Connections",
      tooltipCenter: "★ Hub gene",
      legendCenter: "Hub gene (most connections)",
      legendNormal: "Normal gene",
      legendUnidirectional: "Unidirectional fusion",
      legendBidirectional: "Bidirectional fusion",
      hint: "💡 <strong>Legend:</strong> Node size = total fq · Line width = fusion frequency · Red node = hub gene with most connections · Numbers on lines = fusion count per direction (bidirectional shows A⇄B) · Hover for details · Drag to reposition · Scroll to zoom",
    },
    login: { title: "User Login", username: "Username", password: "Password", button: "Login", error: "Invalid credentials, please try again.", success: "Login successful!" },
    profile: { title: "User Profile", welcome: username => `Hello, ${username}`, logout: "Log Out" },
    fusionDetail: {
      backToList: "Back to list",
      sampleCount: "samples",
      variants: (n) => `${n} breakpoint variants`,
      loading: "Loading data...",
      loadFailTitle: "Load failed",
      loadFailDefault: "No fusion data found",
      debugLabel: "Debug info:",
      debugFusionName: "Fusion gene name",
      debugApiPath: "API path",
      debugRecords: "Records returned",
      debugColumns: "Columns",
      backBtn: "Back to list",
      reloadBtn: "Reload",
      checking: "Checking...",
      available: "Available",
      insufficientData: "Insufficient data",
      analysisTitle: "Optional Fusion Analysis",
      transcriptomeTitle: "Transcriptome Analysis",
      transcriptomeClick: "Click to view gene expression comparison and GO/KEGG enrichment analysis →",
      transcriptomeTooltip1: "Analyze fusion transcript expression and structural features",
      transcriptomeFFPM: "FFPM expression",
      transcriptomeSupportReads: "Supporting reads",
      transcriptomeFusionType: "Fusion type",
      clinicalTitle: "Clinical Data Analysis",
      clinicalClick: "Click to view survival analysis and prognostic assessment →",
      clinicalInsufficient: (pos, neg) => `Insufficient samples (positive:${pos}, negative:${neg})`,
      clinicalTooltip1: "KM survival curve and Cox multivariate regression analysis",
      clinicalPositive: "Positive samples",
      clinicalNegative: "Negative samples",
      clinicalRiskStrat: "Risk stratification",
      clinicalRiskAvail: "Available",
      clinicalRiskNotAvail: "Not available",
      drugTitle: "Drug Sensitivity Analysis",
      drugBadge: "In research",
      drugTooltip1: "Predict drug sensitivity based on fusion genes",
      drugTargeted: "Targeted drug recommendations",
      drugResistance: "Drug resistance assessment",
      drugCombination: "Combination therapy suggestions",
      viewCellLineData: "View Cell Line Data",
      clickDrugSensitivity: "Click to view drug sensitivity analysis →",
      fusionInfoTitle: "Fusion Information",
      variantStatsTitle: "Variant Statistics Overview",
      totalVariants: "Total Variants",
      highestFQ: "Highest FQ",
      junctionDistTitle: "Junction/Spanning Distribution",
      geneNetworkTitle: "Gene Relationship Network",
      upsetTitle: "Co-occurring Fusions Analysis",
      upsetTooltip1: "Shows co-occurrence of this fusion with other fusions across all samples containing it.",
      upsetTooltip2: "Y-axis: Top 10 co-occurring fusions by frequency (current fusion always at bottom).",
      upsetTooltip3: (color) => `Top bar chart: Sample count per intersection set; <span style={{color:'${color}'}}>purple</span> = samples with only the current fusion.`,
      upsetTooltip4: "Right bar chart: Total occurrences of each fusion across all samples.",
      diagramTitle: "Fusion Breakpoint Diagram",
      recommended: "Recommended",
      diagramTooltip1: "Based on Arriba tool design and adapted for SNIFFER result files. ENST transcript annotation uses GENCODE v36 on GRCh38.",
      diagramTooltip2: "The Arriba drawing backend uses GENCODE v36 annotation and GRCh38 protein domains v2.5.1 by default. Variants without usable ENST/CDS transcript IDs may not be drawable.",
      proView: "Pro view",
      interactiveView: "Interactive",
      showBoth: "Show both",
      noVisualizationData: "No visualization data",
      selectRecordHint: "Please select a record via the chart or legend above",
      interactiveDiagramTitle: "Interactive Fusion Structure Diagram",
      proteinTitle: "Fusion Protein Structure Prediction",
      dataTableTitle: (id) => `Detailed Data (Current variant ID: ${id})`,
      fqValueLabel: "FQ value:",
      exportJSON: "Export JSON",
      selectRecordHint2: "Please select a record",
      variantListHeader: (title, n) => `${title} Variant List (${n})`,
      fusionTypeLabel: "Type:",
      chartNoData: "No data",
      dbAvgJunction: (v) => `DB avg Junction: ${v}`,
      fusionJunctionAvg: (v) => `Fusion Junction avg: ${v}`,
      dbAvgSpanning: (v) => `DB avg Spanning: ${v}`,
      fusionSpanningAvg: (v) => `Fusion Spanning avg: ${v}`,
      networkNoData: "No data",
      forwardFusion: "→ Forward fusion",
      reverseFusionLabel: (name) => `↩ Reverse fusion: ${name}`,
      variantFqInfo: (count, fq) => `Variants: ${count}  FQ: ${fq}`,
      nodeInfo: (id, count, fq) => `${id}: ${count} variants, FQ=${fq}`,
      clickToJump: "Click to view details",
      legend5prime: "5' end",
      legend3prime: "3' end",
      legendForward: "Forward",
      legendReverse: "Reverse",
      geneBreakpointTitle: "Gene & Breakpoint Info",
      leftGeneHeader: "5' End (Left Gene)",
      rightGeneHeader: "3' End (Right Gene)",
      geneNameLabel: "Gene:",
      ensgLabel: "ENSG:",
      breakpointLabel: "Breakpoint:",
      dinucLabel: "Dinuc:",
      entropyLabel: "Entropy:",
    },
    arriba: {
      loadingVariants: "Loading variant data...",
      envNotReady: "Arriba environment not ready",
      envCheckConfig: "Cannot generate fusion breakpoint diagram. Please check the following configuration:",
      envConda: (env) => `Conda environment (${env})`,
      envRScript: "draw_fusions.R script",
      envAnnotation: "Annotation file (GTF)",
      envCytobands: "Cytobands file",
      envProteinDomains: "Protein domains file",
      currentVariantId: "Current variant ID:",
      zoomOut: "Zoom out",
      zoomIn: "Zoom in",
      fullscreen: "Fullscreen",
      regenerate: "Regenerate",
      downloadPdf: "Download PDF",
      generating: "Generating Arriba fusion diagram...",
      generatingHint: "This may take 10–30 seconds",
      generateFailed: "Generation failed",
      retry: "Retry",
      selectVariantHint: "Select a variant to view the fusion diagram",
      variantSelectorTitle: "Breakpoint Variants",
      variantCount: (n) => `${n} variants, sorted by FQ`,
      variantLabel: (n) => `Variant ${n}`,
      highestFQ: "Highest FQ",
      leftBreakpoint: "Left BP:",
      rightBreakpoint: "Right BP:",
      currentVariantLabel: "Current:",
      legendTitle: "Legend",
      legend5prime: "5' gene (Gene1)",
      legend3prime: "3' gene (Gene2)",
      legendBreakpoint: "Fusion breakpoint junction",
      legendDomain: "Conserved protein domain",
      close: "Close",
    },
    fusionProtein: {
      loading3d: "Loading 3D viewer...",
      styleCartoon: "Cartoon",
      styleStick: "Stick",
      styleSphere: "Sphere",
      surfaceOn: "Hide surface",
      surfaceOff: "Show surface",
      surfaceLabel: "Surface",
      spinStop: "Stop spinning",
      spinStart: "Start spinning",
      resetView: "Reset view",
      footerStructure: (id) => `🧬 T${id} Fusion Protein Structure`,
      footerEsmfold: "ESMFold prediction",
      footerSurface: "+ Surface layer",
      footerHint: "Drag to rotate · Scroll to zoom · Right-click to pan",
      colorLegendTitle: "Color legend (N→C terminus)",
      colorLegendLabel: "N → C terminus",
      generatingEsmfold: "ESMFold is folding the protein structure...",
      noSequence: "No protein sequence data found",
      noSequenceHint: "fusion_transl field is empty",
      sectionTitle: "Fusion Protein Structure Prediction",
      loadingAlphafold: "Querying AlphaFold database...",
      loadFailed: "Load failed",
      checkingPdb: (id) => `Checking PDB file for T${id}...`,
      generating3d: (id) => `Generating 3D protein structure for T${id}...`,
      cancel: "Cancel",
      esmfoldProgress: "ESMFold is folding the protein structure, this usually takes 1–3 minutes...",
      predictionDone: (id) => `🎉 T${id} Fusion protein structure prediction complete!`,
      fromCache: "Loaded from cache",
      aaCount: (n) => `${n} amino acids`,
      downloadPdb: (id) => `Download T${id}.pdb`,
      repredict: "Re-predict",
      load3dFailed: "Failed to load 3D structure",
      refetch: "Refetch",
      autoPredictFailed: (id) => `T${id} auto-prediction could not be completed`,
      useManualTools: "Please use the tools below for manual prediction",
      retry: "Retry",
      openZjuAF3: "Open ZJU AF3 manually",
      startPredict: (id) => `Start predicting T${id}`,
      onlinePredictTitle: "⚡ Online Fusion Protein 3D Structure Prediction",
      currentVariant: (id) => `Current: T${id}`,
      onlinePredictDesc: "Select a tool below to predict the full fusion protein 3D structure (requires external website)",
      sequenceLabel: "Fusion protein sequence:",
      filteredChars: (n) => `Filtered ${n} invalid characters`,
      overLimit: "Exceeds ESMFold limit",
      copied: "Copied",
      copySequence: "Copy sequence",
      recommended: "Recommended",
      zjuAF3Name: "ZJU AlphaFold3",
      zjuAF3Tagline: "✓ Highest accuracy · Accessible in China",
      zjuAF3Desc: "Zhejiang University AlphaFold3 mirror service. Supports any sequence length, prediction ~5–30 min.",
      zjuAF3Access: "✓ Direct access in China",
      zjuAF3Btn: "Copy sequence & open website",
      esmfoldName: "ESMFold",
      esmfoldTagline: "⚡ Fastest",
      esmfoldDesc: "Meta AI language model prediction. Best for <400aa sequences, ~1–2 min.",
      esmfoldNoLimit: "No usage limit",
      esmfoldBtn: "Copy sequence & open website",
      colabfoldName: "ColabFold",
      colabfoldTagline: "🆓 Free",
      colabfoldDesc: "Free online version of AlphaFold2. Requires Google account, no usage limit, ~10–30 min.",
      colabfoldBtn: "Copy sequence & open website",
      usageTips: "💡 Usage tips:",
      tip1: "Clicking a button automatically copies the sequence to the clipboard and opens the website",
      tip2: "Paste the sequence (Ctrl+V) on the external site to start prediction",
      tip3: "After prediction, download the PDB file and view it with the 3D viewer above or PyMOL",
      singleGeneTitle: "Single Gene Structure",
      dataSource: "Data source",
      dataSourceValue: "AlphaFold v4",
      fusionGeneLabel: "Fusion gene",
      seqLengthLabel: "Sequence length",
      viewOptionsTitle: "View options",
      leftGeneNterm: (g) => `${g} (N-term)`,
      rightGeneCterm: (g) => `${g} (C-term)`,
      openInAlphafold: (g) => `Open ${g} in AlphaFold`,
      waitingStructure: "Waiting for structure data...",
      currentView: (g) => `Current view: ${g}`,
      confidenceLegend: "Confidence legend",
      seqSectionTitle: "Fusion protein amino acid sequence",
      seqOriginalValid: (orig, valid) => `(Original: ${orig} | Valid: ${valid} aa)`,
      hasInvalidChars: "Contains invalid characters",
      copyValidSeq: "Copy valid sequence",
      copyRawSeq: "Copy raw sequence",
      copiedAlert: "Copied!",
      noValidSeq: "No valid sequence",
      errNoAA: "No valid amino acid sequence",
      errSeqTooLong: (n) => `Sequence length (${n}aa) exceeds ESMFold limit (400aa). Please use the external tools below.`,
      errAutoSeqTooLong: (n) => `Sequence length ${n} aa exceeds the current automatic prediction range.`,
      errEsmTooLong: (n) => `Sequence length ${n} aa exceeds the ESMFold automatic prediction range, so automatic prediction is skipped.`,
      errEsmFailed: (msg) => msg ? `ESMFold automatic prediction failed: ${msg}.` : "ESMFold automatic prediction failed.",
      errPredictFailed: "Prediction failed",
      errNoUniProt: "No corresponding UniProt ID found",
      errUniProtQuery: (msg) => `UniProt database query failed: ${msg}`,
      // Local ColabFold / ESMFold preview status
      localAf2Label: "Local AlphaFold2 / ColabFold",
      localColabfoldRunningText: "Local ColabFold is folding the protein structure...",
      localColabfoldProgressText: "Local AlphaFold2 / ColabFold is predicting locally. The first run may be slow because model parameters, JAX compilation, or GPU initialization are being prepared.",
      esmPreviewLabel: "ESMFold · quick preview",
      esmPreviewLoadingTitle: "⚡ Loading ESMFold quick preview...",
      esmPreviewLoadingDesc: "Fetching a quick ESMFold preview while Local ColabFold has started in the background for final prediction.",
      esmPreviewTitle: "ESMFold quick preview",
      esmPreviewNotFinal: "Temporary preview, not the final structure",
      esmPreviewRunningBanner: "ESMFold quick preview is loaded. Local ColabFold is running in the background and will replace it when finished...",
      esmPreviewErrorBanner: "Local ColabFold failed in the background. The ESMFold quick preview is shown for reference.",
      retryColabFold: "Retry ColabFold",
      esmPreviewOverwritten: "ESMFold preview replaced",
      colabfoldStartFailed: "ColabFold failed to start",
      colabfoldNoJobId: "ColabFold did not return a job_id",
      colabfoldTimeoutPreview: "Local AlphaFold2 / ColabFold prediction timed out. The ESMFold preview remains available.",
      colabfoldTimeoutError: "Local AlphaFold2 / ColabFold prediction timed out after polling. Please check the backend log or retry later.",
      alertNoSeq: "No valid amino acid sequence",
      alertCopiedZju: (n) => `Sequence copied! (${n}aa)\n\nOn ZJU AlphaFold3:\n1. Paste into "🧬 Protein sequence"\n2. Click "🚀 Run AlphaFold 3"`,
      alertCopiedEsm: (n) => `Sequence copied! (${n}aa)\n\nPaste sequence on ESMFold website to start prediction`,
      alertCopiedColab: (n) => `Sequence copied! (${n}aa)\n\nPaste sequence in ColabFold Notebook`,
      alertCopyFailed: "Copy failed, please copy manually",
    },
    transcriptome: {
      pageTitle: "Transcriptome Analysis",
      exportData: "Export Data",
      tabExpression: "Gene Expression Comparison",
      tabDifferential: "Differential Expression",
      tabEnrichment: "GO/KEGG Enrichment",
      noData: "No data",
      noExpressionData: "No expression data",
      expressionSectionTitle: "Gene Expression Comparison Chart",
      expressionSectionDesc: "Compare expression levels of fusion genes between fusion-positive (+) and fusion-negative (-) samples. Source: normalized.all.count (TPM)",
      fusionPositiveSamples: "Fusion-positive samples",
      fusionNegativeSamples: "Fusion-negative samples",
      avgFFPM: "Avg FFPM",
      fusionType: "Fusion type",
      fusionPositiveLabel: "Fusion-positive (+)",
      fusionNegativeLabel: "Fusion-negative (-)",
      nMeanStd: (n, mean, std) => `n = ${n} | Mean = ${mean} ± ${std}`,
      loadingExpression: "Loading transcriptome data...",
      loadingDiff: "Running DESeq2 differential expression analysis...",
      loadingDiffHint: "Using count data for analysis, this may take some time",
      loadingEnrich: "Running enrichment analysis...",
      loadingEnrichHint: "Running local R/clusterProfiler analysis...",
      diffMethodTitle: "Analysis Method",
      method: "Method",
      log2fcThreshold: "log2FC threshold",
      fdrThreshold: "FDR threshold",
      dataSource: "Data source",
      diffSummaryTitle: "DEG Summary",
      genesDetected: "Genes tested",
      upRegulated: "Up-regulated",
      downRegulated: "Down-regulated",
      volcanoTitle: "Volcano Plot (DESeq2)",
      up: "Up",
      down: "Down",
      ns: "NS",
      exportPDF: "Export PDF",
      degTableTitle: "Differentially Expressed Genes (Top 100)",
      upLabel: (n) => `Up (${n})`,
      downLabel: (n) => `Down (${n})`,
      export: "Export",
      colGene: "Gene",
      colLog2FC: "log2FC",
      colPValue: "P-value",
      colFDR: "FDR",
      colBaseMean: "Base Mean",
      showingGenes: (start, end, total) => `Showing ${start}–${end} of ${total} genes`,
      noDataDiff: "Unable to load differential analysis data",
      noDataEnrich: "Unable to load enrichment analysis data",
      enrichBanner: "Enrichment analysis based on differentially expressed genes",
      enrichBannerDesc: "Significant differentially expressed genes are merged for unified GO/KEGG enrichment analysis; Up/Down genes are not analyzed separately.",
      enrichPlotNote: "Plots are generated by backend R/clusterProfiler; PNG is used for web preview and PDF can be downloaded directly.",
      combinedDEG: "Combined DEG",
      sourceLabel: "Source",
      mappedGenes: "Mapped genes",
      generatedPlot: "R/clusterProfiler generated plot",
      noEnrichmentPlot: "No significant terms or R plot was not generated",
      noEnrichmentResult: "No enrichment result available",
      noEnrichmentReason: "This can happen when no term passes the adjusted p-value threshold.",
      goBpTitle: "GO Biological Process",
      goMfTitle: "GO Molecular Function",
      goCcTitle: "GO Cellular Component",
      keggTitle: "KEGG Pathway",
      termId: "Term ID",
      geneCount: "Gene Count",
      geneRatio: "Gene Ratio",
      adjustedP: "Adjusted P",
      genesLabel: "Genes",
      upGenesCount: (n) => `Up-regulated: ${n} genes`,
      downGenesCount: (n) => `Down-regulated: ${n} genes`,
      enrichTooltipHint: "💡 Hover over pathway names or bubbles to view full information",
      upEnrichTitle: "Up-regulated Gene Enrichment",
      downEnrichTitle: "Down-regulated Gene Enrichment",
      noSigDEG: "No significant differentially expressed genes found",
      noDotPlotData: (title) => `No ${title} enrichment results`,
      exportPdfFailed: "Export failed: chart element not found",
      exportPdfInstall: "PDF export failed. Ensure html2canvas and jspdf are installed",
    },
    clinical: {
      loading: "Loading clinical data analysis...",
      loadingFusionLabel: "Fusion gene:",
      unavailableTitle: "Clinical data unavailable",
      unavailableFusion: "Fusion gene:",
      unavailablePositive: "Positive samples:",
      unavailableNegative: "Negative samples:",
      unavailableLifelines: (v) => `lifelines available: ${v ? 'Yes' : 'No'}`,
      backToDetail: "Back to detail",
      backToFusionDetail: "Back to fusion detail",
      os: "Overall Survival (OS)",
      efs: "Event-free Survival (EFS)",
      exportReport: "Export Report",
      pageTitle: "Clinical Data Analysis",
      totalSamples: "Total samples:",
      fusionPositive: "Fusion-positive:",
      totalEvents: "Total events:",
      retrying: "Retry",
      switchingType: "Switching analysis type...",
      kmTitle: (label) => label,
      noKmData: "No survival curve data",
      tooltipTime: "Time:",
      tooltipTimeUnit: "years",
      tooltipAtRisk: (pos, neg) => `At risk: Positive ${pos} / Negative ${neg}`,
      followupTime: "Follow-up time (years)",
      survivalProb: "Survival probability",
      fusionPositiveLabel: "Fusion-positive",
      fusionNegativeLabel: "Fusion-negative",
      positiveGroup: "Fusion-positive group",
      negativeGroup: "Fusion-negative group",
      sampleN: "n:",
      events: "Events:",
      medianSurvival: "Median survival:",
      medianNotReached: "Not reached",
      survivalYears: "years",
      survival5y: "5-year survival:",
      coxError: (msg) => msg || "Cox regression analysis failed",
      coxTitle: "Cox Multivariate Regression",
      coxModel: "Model: Surv(time, event) ~ fusion_status + age + sex + risk_group",
      cIndex: "C-index:",
      sampleSize: "Sample size:",
      eventCount: "Events:",
      colVariable: "Variable",
      colPValue: "P-value",
      colSignificance: "Significance",
      significant: "✓ Significant",
      notSignificant: "Not significant",
      hrExplain: "HR (hazard ratio): HR > 1 indicates higher event risk; HR < 1 indicates lower risk.",
      forestTitle: "HR",
      forestLoadingRef: "Loading reference fusion data...",
      forestCurrentFusion: "Current fusion",
      forestOncogenicRef: "High risk Fusion",
      forestFavorableRef: "Low risk Fusion",
      forestOncogenicLabel: "Oncogenic Fusions",
      forestFavorableLabel: "Tumor Suppressor Fusions",
      forestNote: "Hazard ratio (HR) compares event risk between groups; HR > 1 indicates higher risk, HR < 1 lower risk.",
      osUnavailable: "Overall Survival data unavailable",
      efsUnavailable: "Event-Free Survival data unavailable",
      forestWarningText: "⚠ This HR estimate is unreliable due to quasi-complete separation (very few events in the positive group). The KM survival curves above remain valid — please refer to those for prognosis assessment.",
      favorablePrognosis: "Favorable prognosis",
      unfavorablePrognosis: "Unfavorable prognosis",
      clinicalSummaryTitle: "Clinical Feature Summary",
      patientsCount: (n) => `(${n} patients)`,
      demographicsTitle: "Demographics",
      genderDist: "Gender distribution",
      diagnosisAge: "Diagnosis age (years)",
      median: "Median:",
      fabClassification: "FAB classification",
      riskStratTitle: "Risk stratification",
      outcomesTitle: "Outcomes",
      survivalStatus: "Survival status",
      overallSurvivalTime: "Overall survival time",
      medianYears: (v) => `Median: ${v} years`,
      analysisNotesTitle: "Analysis notes",
      kmNote: "Compares survival between fusion-positive and fusion-negative patients. Log-rank test is used to assess statistical significance.",
      coxNote: "Cox multivariate regression: Evaluates the independent effect of fusion gene status on survival after controlling for age, sex, and risk group. HR < 1 indicates better prognosis, HR > 1 indicates worse prognosis.",
      timeNote: "Note: Time unit converted to years (raw data in days/365). p < 0.05 is considered statistically significant.",
    },
    sniffer: {
      loginRequired: "SNIFFER requires login",
      loginDesc: "Please log in to use the SNIFFER fusion gene detection algorithm",
      loginBtn: "Login",
      loggedInAs: (u) => `Logged in: ${u}`,
      analyzing: "Please do not close this page. Results will appear automatically when analysis is complete.",
      noData: "No data",
      noDataHint: "Please upload a CSV or XLSX file",
      analysisComplete: "Analysis Complete",
      snifferResults: "SNIFFER detection results",
      fusionRecords: "Fusion records",
      uniqueFusions: "Unique fusions",
      genesInvolved: "Genes involved",
      chromosomes: "Chromosomes",
      topFusionsTitle: "Detected fusion genes (Top 10)",
      downloadResults: "Download results",
      newAnalysis: "New analysis",
      panelTitle: "SNIFFER Analysis",
      tabTsv: "TSV Fusion Results",
      tabFastq: "FASTQ Full Analysis",
      tsvModeTitle: "TSV Mode",
      tsvModeDesc: (e1, e2) => `Upload fusion result files from StarFusion/Arriba, use SNIFFER for ${e1} and ${e2}.`,
      tsvModeE1: "fusion similarity filtering",
      tsvModeE2: "accuracy scoring",
      fastqModeTitle: "FASTQ Mode",
      fastqModeDesc: (e1) => `Upload paired FASTQ sequencing files to run the full SNIFFER pipeline for fusion gene detection. Supports ${e1}`,
      fastqModeE1: "paired-end sequencing",
      dropHint: "Drag file here",
      dropHint2: "or click below to select a file",
      fusionFileLabel: "Fusion result file (TSV/CSV/TXT)",
      read1Label: "Read 1 (Forward)",
      read2Label: "Read 2 (Reverse)",
      uploading: "Uploading file...",
      uploadingBtn: "Uploading...",
      startAnalysis: "Start Analysis",
      reset: "Reset",
      usageTitle: "How to use",
      tsvStep1: "1. Upload fusion detection result file (StarFusion/Arriba output)",
      tsvStep2: "2. SNIFFER will perform sequence similarity analysis and fusion scoring",
      tsvStep3: "3. Download result file with confidence scores",
      fastqStep1: "1. Upload paired FASTQ files (Read 1 and Read 2)",
      fastqStep2: "2. Click \"Start Analysis\" to launch the SNIFFER detection pipeline",
      fastqStep3: "3. Wait for analysis to complete, then download the fusion gene detection report",
      fqPanelTitle: "Fusion FQ Bar Chart",
      clearData: "Clear data",
      fqDesc1: "Upload a CSV file containing",
      fqDesc2: "and",
      fqDesc3: "columns",
      fqUploadHint: "Click to upload FQ data file",
      fqUploadHint2: "Supports CSV, XLSX formats",
      fqRecords: (n) => `${n.toLocaleString()} records`,
      showLabel: "Show:",
      chartNote1: "• Grey bars indicate fusions with FFPM ≥ 0.1 (high expression)",
      chartNote2: "• Red bars indicate fusions with FFPM < 0.1 (low expression, possible false positives)",
      chartNote3: "• Italic labels indicate fusions with only low-expression records",
      analyzingMsg: (msg) => msg || "Analyzing...",
      errLoginExpired: "Session expired, please log in again",
      errUploadFailed: "Upload failed",
      errUploadRetry: "Upload failed, please try again",
      errNetwork: "Network error, please check connection",
      errDownload: "Download failed",
      errCsvOnly: "Please upload a CSV file",
      errParseFailed: (msg) => `File parsing failed: ${msg}`,
      taskResuming: "Resuming task...",
      taskStarting: "Starting task...",
    },
    chromosomeDetail: {
      loading: (chr) => `Loading ${chr} chromosome data...`,
      loadFailTitle: "Loading Failed",
      backToHome: "Back to Home",
      chrTitle: (chr) => `${chr} Chromosome`,
      chrNameLabel: "Chromosome Name",
      totalFusions: "Total Fusion Genes",
      genesInvolved: "Genes Involved",
      searchPlaceholder: "Search gene name, fusion name, sample name...",
      searchBtn: "Search",
      clearBtn: "Clear",
      fusionListTitle: "Fusion Gene List",
      searchLabel: (q) => `(Search: "${q}")`,
      sortFieldFq: "Frequency",
      sortFieldFfpm: "Avg FFPM",
      sortDesc: "descending",
      sortAsc: "ascending",
      sortInfo: (fieldLabel, orderLabel) => `Sorted by ${fieldLabel} ${orderLabel}`,
      loadingMore: "Loading...",
      noData: "No data available",
      noDataHint: "No fusion genes found on this chromosome",
      colFusionName: "Fusion Name",
      colLeftGene: "Left Gene",
      colLeftBreakpoint: "Left Breakpoint",
      colRightGene: "Right Gene",
      colRightBreakpoint: "Right Breakpoint",
      colChrBand: "Chr Band",
      colAnnots: "Annotations",
      colFrequency: "Frequency",
      showingRange: (start, end, total) => `Showing ${start} – ${end} of ${total}`,
      firstPage: "First",
      lastPage: "Last",
      goToPage: "Go to",
      pageInfo: (totalPages) => `page / ${totalPages} pages total`,
      fetchError: "Failed to fetch chromosome data",
    },
    geneFunction: {
      loading: (gene) => `Loading ${gene} gene info...`,
      notFound: "Gene info not found",
      queryFailed: "Query failed",
      title: (gene) => `${gene} Gene Function`,
      fullName: "Full name:",
      type: "Type:",
      summary: "Summary:",
      alias: "Aliases:",
    },
    fusionDeletedDetail: {
      loading: "Loading...",
      loadFailTitle: "Load Failed",
      notFoundData: "No data found",
      backBtn: "Back",
      variantsCount: (n) => `${n} variants`,
      filterReasonTitle: "⚠️ Reason for Low Confidence",
      filterReasonHint: "This fusion gene did not pass SNIFFER quality filtering. Results are for reference only.",
      variantCount: "Variants",
      totalFq: "Total fq",
      variantListTitle: (n) => `📋 Variant List (${n} variants, sorted by fq, click for details)`,
      tableHeaders: ['ID', 'Left Breakpoint', 'Right Breakpoint', 'fq', 'Junction', 'Spanning', 'Protein Type', 'Filter'],
      geneBreakpointTitle: "Gene & Breakpoint Info",
      leftGeneHeader: "5' End (Left Gene)",
      rightGeneHeader: "3' End (Right Gene)",
      geneNameLabel: "Gene:",
      ensgLabel: "ENSG:",
      breakpointLabel: "Breakpoint:",
      dinucLabel: "Dinuc:",
      entropyLabel: "Entropy:",
      annotLabel: "Annotations:",
      spliceTypeLabel: "Splice type:",
      largeAnchorLabel: "Large anchor:",
      protFusionTypeLabel: "Protein fusion type:",
      arribaTitle: "Fusion Breakpoint Diagram (Arriba)",
      arribaRecommended: "Recommended",
      dataTableTitle: (id) => `Detailed Data (TF${id || 'N/A'})`,
      exportJSON: "Export JSON",
      selectRecordHint: "Please select a record",
      paginationRange: (start, end, total) => `${start}-${end} of ${total}`,
    },
    cellLineDetail: {
      viewTargetData: "View Target Data",
      geneInfoTitle: "Gene Info",
      geneBreakpointTitle: "Gene & Breakpoint Info",
      leftGeneHeader: "5' End (Left Gene)",
      rightGeneHeader: "3' End (Right Gene)",
      geneNameLabel: "Gene:",
      ensgLabel: "ENSG:",
      breakpointLabel: "Breakpoint:",
      dinucLabel: "Dinuc:",
      fusionNameLabel: "Fusion Name",
      leftGeneLabel: "Left Gene",
      rightGeneLabel: "Right Gene",
      functionLeftLabel: "Function Left",
      functionRightLabel: "Function Right",
      cdsLeftLabel: "CDS Status Left",
      cdsRightLabel: "CDS Status Right",
      avgFfpmLabel: "Avg FFPM",
      totalFqLabel: "Total FQ",
    },
    drugSensitivity: {
      pageTitle: "Drug Sensitivity Analysis",
      dataSourceLabel: "Data source:",
      dataSourceGDSC: "(Genomics of Drug Sensitivity in Cancer) Cell line drug sensitivity",
      backToDetail: "Back to Detail",
      disclaimer: "Disclaimer",
      disclaimerText: "The GDSC cell line drug sensitivity data shown on this page is from the Genomics of Drug Sensitivity in Cancer (GDSC) project. The correlation analysis between gene expression and drug sensitivity only reflects statistical associations at the cell line level and does not represent causal relationships at the clinical level. This information is for research reference only and does not constitute clinical treatment advice.",
      cannotParseGene: "Cannot parse genes from fusion name",
      expectedFormat: "Expected format: GENE1--GENE2",
      githubLabel: "GitHub project:",
    },
    drugGeneSearch: {
      pageTitle: "Drug-Gene Sensitivity Analysis",
      // subtitle 分两段以便在中间插入 <a> 链接
      pageSubtitlePrefix: "Based on ",
      pageSubtitleSuffix: " · Search a gene or fusion gene to explore drug sensitivity in cancer cell lines",
      searchBoxTitle: "Search Gene / Fusion Gene",
      searchHint: "Single gene:",
      searchHintFusion: "Fusion:",
      placeholder: "Enter gene name or fusion name, e.g. RUNX1--RUNX1T1",
      recentSearches: "Recent searches",
      analyze: "Analyze",
      examples: "Examples:",
      fusionFormatTitle: "Fusion Gene Format",
      fusionFormatDesc: "Supports fusion / gene analysis modes",
      geneFormatTitle: "Single Gene Format",
      geneFormatDesc: "Gene expression analysis mode",
      resultsFor: "Results for:",
      fusionBadge: "Fusion",
      geneBadge: "Gene",
      clear: "Clear",
      emptyTitle: "Enter a gene or fusion name to start analysis",
      emptySubtitle: "Results will appear here",
      disclaimerTitle: "Disclaimer",
      disclaimerText: "The GDSC cell line drug sensitivity data is from the Genomics of Drug Sensitivity in Cancer (GDSC) project. Correlation analysis between gene expression and drug sensitivity reflects statistical associations at the cell line level only and does not represent causal clinical relationships. For research reference only; not clinical advice.",
      invalidInput: "Please enter a valid gene (e.g. RUNX1) or fusion (e.g. RUNX1--RUNX1T1)",
      githubLabel: "GitHub project:",
    },
    gdsc: {
      title: "GDSC Cell Line Drug Sensitivity Analysis",
      dataSource: "Data source:",
      dataSourceSuffix: "(Genomics of Drug Sensitivity in Cancer)",
      analyzeGene: "Analysis gene:",
      analyzeFusion: "Analyze Fusion",
      fusionPositive: "Fusion Positive",
      fusionNegative: "Fusion Negative",
      highExpression: "High Expression",
      lowExpression: "Low Expression",
      metricZScore: "Z_SCORE (Z-score)",
      metricLnIc50: "LN_IC50",
      metricAuc: "AUC",
      metricRmse: "RMSE",
      descZScore: "Z-score: Standardized score measuring drug sensitivity relative to the mean. Positive values indicate more resistant than average, negative values indicate more sensitive.",
      descLnIc50: "LN_IC50: Natural log of IC50, representing the drug concentration needed to inhibit 50% cell growth. Higher values indicate more resistance.",
      descAuc: "AUC: Area under the dose-response curve. Higher values indicate more resistance.",
      descRmse: "RMSE: Fitting error of the dose-response model.",
      splitMedian: "Median",
      splitUpperTertile: "Upper Tertile",
      splitLowerTertile: "Lower Tertile",
      splitUpperQuartile: "Upper Quartile",
      splitLowerQuartile: "Lower Quartile",
      metricLabel: "Metric:",
      groupLabel: "Grouping:",
      sortLabel: "Sort:",
      sortSuffix: " sort",
      noSort: "No sort",
      reset: "Reset",
      fusionGroupMode: "Fusion Grouping Mode",
      fusionGroupDesc: (name) => `Based on whether cell lines carry the `,
      fusionGroupDescBold: (name) => name,
      fusionGroupDescMid: " fusion, grouped into",
      fusionGroupDescPos: (n) => ` Fusion Positive (${n})`,
      fusionGroupDescAnd: " and",
      fusionGroupDescNeg: (n) => ` Fusion Negative (${n})`,
      fusionGroupDescEnd: ".",
      positiveCellLines: "Positive cell lines: ",
      fusionNotDetectedCCLE: "This fusion was not detected in CCLE cell lines. Please view drug sensitivity for the related genes.",
      dataNotConfigured: "GDSC Data Not Configured",
      dataNotConfiguredDesc1: "Please place ",
      dataNotConfiguredDesc2: " and ",
      dataNotConfiguredDesc3: " in the backend ",
      dataNotConfiguredDesc4: " directory",
      loadingData: (gene) => `Loading ${gene} GDSC data...`,
      geneNotFound: (gene) => `Gene ${gene} not found in GDSC database`,
      totalSamples: "Total Samples",
      drugCount: "Drug Count",
      fusionScatterTitle: (name) => `Drug sensitivity scatter for ${name} fusion grouping`,
      geneScatterTitle: (gene) => `Drug sensitivity scatter grouped by ${gene} expression (FPKM)`,
      noDrugData: "No drug data available",
      drugDetails: "Drug Details",
      clickDrugDot: "Click a drug dot to view",
      drugDetailInfo: "Drug Detail Information",
      drugName: "Drug Name",
      target: "Target",
      pathway: "Pathway",
      meanLabel: "Mean",
      meanSdLabel: "Mean ± SD",
      diffPValue: "Diff p-value",
      sigDiffMsg: (labelA, labelB, metric) => `✓ This drug shows significant ${metric} difference between ${labelA}/${labelB} (p < 0.05)`,
      noSigDiffMsg: (labelA, labelB, metric) => `No significant ${metric} difference between ${labelA}/${labelB} (p ≥ 0.05)`,
      clickDrugDotView: "Click a drug dot in the scatter plot",
      viewDrugInfo: "View drug detail information",
      drugAnalysisTitle: (name) => `Drug "${name}" Detailed Analysis`,
      switchDrugHint: "Click other drug dots to switch",
      correlationMetricLabel: "Correlation metric:",
      correlationTitle: (gene, drug, metric) => `${gene} expression vs ${drug} ${metric} correlation`,
      corrCoeff: "Correlation (r):",
      pValue: "P-value:",
      sampleCountN: "Sample count (n):",
      significance: "Significance:",
      significant: "(Significant)",
      notSignificant: "(Not significant)",
      insufficientData: "Insufficient data",
      drugGroupDistTitle: (drug, labelA, labelB, metric) => `"${drug}" ${metric} distribution in ${labelA}/${labelB}`,
      samplesStat: (label, n) => `${label}: ${n} samples`,
      expressionDistTitle: (gene) => `${gene} Expression Distribution`,
      expressionAxisLabel: "Expression (FPKM)",
      otherCategory: "Other",
      groupHistology: "Histology",
      groupSite: "Site",
      clickForAnalysis: "Click a drug dot for detailed analysis",
      analysisIncludes: "Includes correlation analysis, group comparison and drug details",
      fusionStatsLine: (name, labelA, highN, labelB, lowN, metric) => `Fusion: ${name}; ${labelA}: ${highN}; ${labelB}: ${lowN}; Metric: ${metric}`,
      geneStatsLine: (gene, total, labelA, highN, labelB, lowN, metric, split) => `Gene: ${gene}; Total: ${total}; ${labelA}: ${highN}; ${labelB}: ${lowN}; Metric: ${metric}; Grouping: ${split}`,
    },
  },

  zh: {
    siteName: "Fusion Gene Portal",
    nav: { home: "首页", search: "搜索", sniffer: "SNIFFER", login: "登录" },
    home: {
      loading: "正在加载数据...",
      uniqueFusions: "唯一融合基因",
      uniqueGenes: "涉及基因数量",
      sampleCount: "样本数",
      searchTitle: "🔍 搜索融合基因",
      searchPlaceholder: "输入基因名称或融合名称进行搜索...",
      searchButton: "搜索",
      searchTip: "",
      suggestionTypeGene: "基因",
      suggestionTypeFusion: "融合",
      circosTitle: "🧬 染色体融合 Circos 图",
      circosSubtitle: "选择染色体查看该染色体上的融合基因",
      selectChromosome: "选择染色体",
      top100Title: "📊 高频融合基因 (Top 100)",
      top100Subtitle: "按频次降序排列",
      fqLabel: "Frequency (fq)",
      cellLineSampleCount: "细胞系样本",
      showingRange: (start, end, total) => `显示 ${start} – ${end} 条，共 ${total} 条`,
      todayHighlight: "⭐ 今日融合基因",
      fusionName: "融合名称",
      leftGene: "左侧基因",
      rightGene: "右侧基因",
      frequency: "频率 (fq)",
      viewDetails: "查看详情 →",
      snifferTitle: "🔬 SNIFFER 算法简介",
      snifferIntro: "SNIFFER算法是一种用于从测序数据中检测基因融合的先进方法。它可以自动识别融合断点，并提供全面的融合事件可视化，帮助研究者筛选具有生物学意义的融合基因用于深入分析。",
      literatureTitle: "📚 浙江大学应美丹教授课题组融合基因相关文献",
      literatureList: [
        { href: "https://pubmed.ncbi.nlm.nih.gov/?term=A%20novel%20gene%20fusion%20RUNX1/ZNF423%20promotes%20leukemic%20relapse%20of%20NUP98-rearranged%20AML", color: "blue", title: "A novel gene fusion RUNX1/ZNF423 promotes leukemic relapse of NUP98-rearranged AML", desc: "RUNX1/ZNF423 融合促进 NUP98 重排 AML 白血病复发的机制研究" },
        { href: "https://pubmed.ncbi.nlm.nih.gov/?term=Deneddylation%20of%20PML/RARa%20Reconstructs%20Functional%20PML%20Nuclear%20Bodies%20via%20Orchestrating%20Phase%20Separation%20to%20Eradicate%20APL", color: "purple", title: "Deneddylation of PML/RARa Reconstructs Functional PML Nuclear Bodies via Orchestrating Phase Separation to Eradicate APL", desc: "PML/RARa 去 NEDD 化重建功能性 PML 核体，并通过调控相分离清除 APL 的机制研究" },
        { href: "https://pubmed.ncbi.nlm.nih.gov/42151502/", color: "green", title: "Targeting fusion proteins in solid tumors: from oncogenic mechanisms to clinical interventions", desc: "Acta Pharmacologica Sinica，2026 - 应美丹教授课题组关于实体瘤融合蛋白致癌机制与靶向干预的综述" },
        { href: "https://pubmed.ncbi.nlm.nih.gov/39227737/", color: "orange", title: "Palmitoyltransferase ZDHHC3 is essential for the oncogenic activity of PML/RARa in acute promyelocytic leukemia", desc: "Acta Pharmacologica Sinica，2025 - 围绕白血病 PML/RARa 融合蛋白致癌活性的机制研究" }
      ],
      deletedTitle: "🚫 低可信度融合基因 (Top 100)",
      deletedSubtitle: "来自 SNIFFER 筛选过滤的候选融合基因 · 按频次降序",
      filterLabel: "Filter 类型：",
      filterAll: "全部（不筛选）",
      filterClear: "清除",
      currentFilter: "当前筛选：",
      totalCount: (n) => `共 ${n} 条`,
      deletedLoading: "正在加载低可信度融合基因...",
      noData: "暂无数据",
      noDataForFilter: "该 Filter 类型下没有融合基因",
      clickToFilter: (val) => `点击筛选: ${val}`,
      deletedShowingRange: (start, end, total) => `显示 ${start} – ${end} 条，共 ${total} 条`,
      // ── Cell Line & Disease filter (Home) ──
      targetBannerTitle: "SNIFFER Target 分析",
      cellLineBannerTitle: "SNIFFER 细胞系分析",
      targetBannerSubtitle: "基于儿童 TARGET AML 测序数据，通过 SNIFFER 算法检测到的融合基因结果",
      cellLineBannerSubtitle: "基于 1019 个 CCLE 细胞系样本，通过 SNIFFER 算法检测到的融合基因结果",
      cellLineModuleSubtitle: "SNIFFER 处理 CCLE 中 1019 个细胞系样本得到数据",
      diseaseTypesLabel: "疾病类型",
      cellLineSamplesLabel: "细胞系样本数",
      tissueOriginsLabel: "组织来源",
      filterByDiseaseType: "按疾病类型筛选",
      clearSelection: "清空",
      selectAll: "全选",
      deselectAll: "取消全选",
      selectedDiseasesCount: (n) => `已选 ${n} 种疾病：`,
      pleaseSelectDisease: "请先选择疾病类型",
      drawSelectedDiseases: (n) => `选中的 ${n} 种疾病 Top 20 融合基因`,
      diseasesFilterDesc: (n) => `${n} 种疾病`,
      cellLineFilterDesc: (name) => `细胞系: ${name}`,
      clearFilter: "清除筛选",
      searchByCellLine: "按细胞系搜索",
      downloadCellLineData: (name) => `下载 ${name} 相关数据 (CSV)`,
      noFusionForFilter: "该筛选条件下无融合基因数据",
      chartNoDataForFilter: "该筛选条件下暂无数据",
      allDiseases: (n) => `全部疾病 (${n})`,
      allCellLines: (n) => `全部细胞系 (${n})`,
    },
    search: {
      pageTitle: "🔬 融合基因搜索",
      pageSubtitle: "搜索、筛选和可视化融合基因数据",
      modePass: "PASS",
      modeGlobal: "全局搜索",
      modeLabelPass: "🧬高可信度融合基因（PASS）· ID格式: TP+编号",
      modeLabelGlobal: "🌐同时搜索 PASS 数据库 + FILTER 数据 · ID格式: TP+编号 / TF+编号",
      placeholderPass: (idEnabled) => `搜索基因名称、融合名称或编号...`,
      placeholderGlobal: (idEnabled) => `全局搜索基因名称、融合名称或编号...`,
      suggestionTypeGene: "基因",
      suggestionTypeFusion: "融合",
      idSearchOn: "ID搜索 开",
      idSearchOff: "ID搜索 关",
      idSearchTitleOn: (prefix) => `ID搜索已开启：${prefix}+编号 将精确定位记录`,
      idSearchTitleOff: "ID搜索已关闭",
      searching: "搜索中...",
      fuzzySearch: "🔍 模糊搜索",
      exactSearch: "🎯 精准搜索",
      hintExact: "🎯 精准搜索：只匹配基因名精确等于搜索词的融合（如 RP2 只搜以 RP2 为一侧基因的融合）",
      hintFuzzy: "🔍 模糊搜索：搜索所有包含关键字的融合基因",
      idSearchEnabledHint: (prefix) => `· ID搜索开启：${prefix}+编号可精确定位`,
      idSearchDisabledHint: "· ID搜索已关闭",
      advancedFilter: "🎯 高级筛选",
      advancedFilterActive: "(已启用)",
      advancedHint: "💡 可单独使用高级筛选搜索，也可与上方关键字组合联动",
      advancedSearchOnly: "🎯 单独执行高级搜索",
      filterBy: "筛选方式：",
      byChromosome: "🧬 按染色体筛选",
      byGene: "🔬 按基因筛选",
      leftChromosome: "左侧染色体",
      rightChromosome: "右侧染色体",
      allChromosomes: "全部染色体",
      leftGeneLabel: "🔬 左侧基因",
      rightGeneLabel: "🔬 右侧基因",
      leftGenePlaceholder: "输入左侧基因名称...",
      rightGenePlaceholder: "输入右侧基因名称...",
      sortField: "排序字段",
      sortOrder: "排序顺序",
      sortDesc: "降序 (高到低)",
      sortAsc: "升序 (低到高)",
      combinedSearch: "当前组合搜索：",
      keywordBadge: (q) => `🔍 关键字: ${q}`,
      leftChrBadge: (c) => `🧬 左: ${c}`,
      rightChrBadge: (c) => `🧬 右: ${c}`,
      leftGeneBadge: (g) => `🔬 左基因: ${g}`,
      rightGeneBadge: (g) => `🔬 右基因: ${g}`,
      andActive: "→ 同时生效",
      resultsTitle: (mode) => mode === 'pass' ? '✅ PASS 搜索结果' : '🌐 全局搜索结果',
      totalFound: (n) => `共找到 ${n} 个融合基因`,
      tableHeadersPass: ['编号', '融合名称', '左侧基因', '左侧断点', '右侧基因', '右侧断点', '注释', '频率'],
      legendPass: "PASS 数据（Fusion DB）",
      legendFilter: "FILTER 数据（fusiondeleted）",
      legendExpand: "▶ 点击行首箭头展开同名变体",
      variantsCount: (n) => `${n} 个其他变体`,
      loadingVariants: "正在加载变体数据...",
      circosTitle: "🎨 融合基因 Circos 图",
      circosGlobalTitle: "🎨 全局搜索 Circos 图",
      circosGlobalSubtitle: "包含 PASS + FILTER 数据，按 fq 降序",
      displayRange: "显示范围：",
      junctionTitle: "📊 Junction & Spanning Reads",
      junctionGlobalTitle: "📊 全局 Junction & Spanning Reads",
      junctionGlobalSubtitle: "包含 PASS + FILTER 数据，按总量降序",
      showTop: "显示前：",
      itemsOfTotal: (n) => `个 / 共 ${n}`,
      fusionsOfTotal: (n) => `个融合 / 共 ${n}`,
      networkTitle: "🌐 基因融合网络图",
      networkGlobalTitle: "🌐 全局融合网络图",
      networkGlobalSubtitle: "包含 PASS + FILTER 数据",
      showingRange: (start, end, total) => `显示第 ${start} - ${end} 条，共 ${total} 条`,
      firstPage: "首页",
      lastPage: "末页",
      noResultsTitle: "未找到匹配结果",
      noResultsHint: "请尝试调整搜索条件或使用其他搜索方式",
      initialTitlePass: "开始搜索 PASS 融合基因",
      initialTitleGlobal: "开始全局搜索融合基因",
      initialSubtitlePass: "高可信度融合基因数据库",
      initialSubtitleGlobal: "同时搜索 PASS 数据库 + FILTER 数据，结果统一展示",
      loadingPass: "正在搜索...",
      loadingGlobal: "正在搜索 PASS + FILTER 数据...",
      descSearch: (q) => `搜索: "${q}"`,
      descLeftChr: (c) => `左侧染色体: ${c}`,
      descRightChr: (c) => `右侧染色体: ${c}`,
      descLeftGene: (g) => `左侧基因: ${g}`,
      descRightGene: (g) => `右侧基因: ${g}`,
      // ── Cell Line DB (Search page) ──
      cfModeLabelCellLine: "🧫 Cell Line DB — 搜索 CCLE 细胞系融合基因数据库",
      cfSearchPlaceholder: "搜索融合基因名称或 CL 编号（e.g. YWHAE--CRK, CL18）",
      cfCellLinePlaceholder: "细胞系（e.g. MCF7）",
      cfSearching: "搜索中",
      cfSearchBtn: "搜索",
      cfSearchHint: "基于 CCLE 1019 个细胞系样本 · 融合名 / 细胞系模糊匹配",
      cfResultsSummary: (records, fusions) => `${records} 条记录 · ${fusions} 个融合基因`,
      cfDiseaseFilterToggle: "🏥 疾病类型筛选",
      cfDiseasesSelected: (n) => `${n} 种已选`,
      cfSearchingLoading: "正在搜索 Cell Line 数据库...",
      cfNoResults: "未找到匹配的融合基因",
      cfNoResultsHint: "请尝试更改搜索条件",
      cfInitialHint: "输入融合基因名称、CL 编号、细胞系名称或疾病类型进行搜索",
      cfInitialHint2: "支持三种条件单独或组合查询 · 支持括号内逗号的疾病名精确匹配",
      cfResultsTitle: "🧫 Cell Line DB 搜索结果",
      cfResultsCount: (fusions, records) => `共 ${fusions} 个融合基因 · ${records} 条细胞系记录`,
      cfSearchContentLabel: (q) => `搜索内容：${q}`,
      cfDiseasesFiltered: (n) => `${n} 种疾病已筛选`,
      cfExpandable: "可展开（多个细胞系样本）",
      cfClickHint: "点击融合名称 → 详情页（有 PASS 数据则跳转 PASS，否则展示 Cell Line 详情）",
      cfFusionClickTitle: "跳转到融合详情页（PASS 数据库优先，否则展示 Cell Line 详情）",
      cfVariantCount: (n) => `${n} 个细胞系样本`,
      cfShowingRange: (start, end, total) => `显示 ${start}–${end} / 共 ${total} 个融合`,
      cfFilterByDiseaseType: "按疾病类型筛选",
      cfClearSelection: "清空",
      cfSelectAll: "全选",
      cfDeselectAll: "取消全选",
      cfSelectedDiseasesCount: (n) => `已选 ${n} 种疾病：`,
      cfPleaseSelectDisease: "请先选择疾病类型",
      cfFilterSelectedDiseases: (n) => `筛选选中的 ${n} 种疾病`,
      cfAllCellLines: (n) => `全部细胞系 (${n})`,
      cfAllDiseases: (n) => `全部疾病 (${n})`,
      cfAllTissues: (n) => `全部组织 (${n})`,
    },
    sniffer: {
      title: "SNIFFER 分析",
      hint: "上传一个融合基因CSV文件进行即时分析（数据不会被保存）：",
      button: "开始分析",
      summary: (total, genes, chrs) => `检测到 **${total}** 个融合事件，涉及 **${genes}** 个独立基因，跨越 **${chrs}** 条染色体。`,
      chartTitle: "上传数据的 Circos 图",
      failure: "分析失败，请检查文件格式。",
      loginRequired: "请登录后使用 SNIFFER 算法服务。",
      loginButton: "前往登录"
    },
    circos: {
      tooltipChr: (name, count) => `点击筛选 ${name} (当前结果中有 ${count} 个融合)`,
      tooltipFusion: (name, fq, ffpm) => `${name} | fq: ${fq} | FFPM: ${ffpm} | 点击查看详情`,
      legendTitle: "融合基因 Circos 图",
      legendSubtitle: (n) => `显示 ${n} 个融合（按 fq 降序排列）`,
      legendTip: "💡 点击染色体弧添加筛选条件 | 点击连线查看融合详情 | 线条粗细表示频率",
    },
    junction: {
      tooltipClickDetail: "点击查看详情",
      noData: "暂无数据",
      hint: "💡 <strong>提示：</strong>柱状图使用 log₂ 缩放显示以优化视觉效果，数值标签显示原始计数。蓝色柱表示 Junction Reads，绿色柱表示 Spanning Fragments。",
      hintClick: "点击融合名称或柱子可查看详情。",
    },
    network: {
      noData: "暂无数据",
      tooltipTotalFq: "总fq",
      tooltipConnections: "连接数",
      tooltipCenter: "★ 中心基因",
      legendCenter: "中心基因（连接最多）",
      legendNormal: "普通基因",
      legendUnidirectional: "单向融合",
      legendBidirectional: "双向融合",
      hint: "💡 <strong>图例说明：</strong>节点大小 = 总fq值 · 线条粗细 = 融合出现次数 · 红色节点 = 连接数最多的中心基因 · 线上数字 = 各方向融合次数（双向显示 A⇄B） · 鼠标悬停查看详情 · 拖拽调整布局 · 滚轮缩放",
    },
    login: { title: "用户登录", username: "用户名", password: "密码", button: "登录", error: "账户或密码错误，请重试。", success: "登录成功！" },
    profile: { title: "用户信息", welcome: username => `您好，${username}`, logout: "退出登录" },
    fusionDetail: {
      backToList: "返回列表",
      sampleCount: "样本数",
      variants: (n) => `共 ${n} 个断点变体`,
      loading: "正在加载数据...",
      loadFailTitle: "加载失败",
      loadFailDefault: "未找到相关融合数据",
      debugLabel: "调试信息：",
      debugFusionName: "融合基因名",
      debugApiPath: "API路径",
      debugRecords: "返回记录数",
      debugColumns: "列数",
      backBtn: "返回列表",
      reloadBtn: "重新加载",
      checking: "检查中...",
      available: "可用",
      insufficientData: "数据不足",
      analysisTitle: "可选融合分析",
      transcriptomeTitle: "转录组分析",
      transcriptomeClick: "点击查看基因表达量比较和GO/KEGG富集分析 →",
      transcriptomeTooltip1: "分析融合转录本的表达水平和结构特征",
      transcriptomeFFPM: "FFPM表达量",
      transcriptomeSupportReads: "支持读段",
      transcriptomeFusionType: "融合类型",
      clinicalTitle: "临床数据分析",
      clinicalClick: "点击查看生存分析和预后评估 →",
      clinicalInsufficient: (pos, neg) => `样本量不足 (阳性:${pos}, 阴性:${neg})`,
      clinicalTooltip1: "KM生存曲线和Cox多因素回归分析",
      clinicalPositive: "阳性样本",
      clinicalNegative: "阴性样本",
      clinicalRiskStrat: "风险分层",
      clinicalRiskAvail: "可用",
      clinicalRiskNotAvail: "不可用",
      drugTitle: "药敏分析",
      drugBadge: "研究中",
      drugTooltip1: "基于融合基因预测药物敏感性",
      drugTargeted: "靶向药物推荐",
      drugResistance: "耐药性评估",
      drugCombination: "联合用药建议",
      viewCellLineData: "查看 Cell Line 数据",
      clickDrugSensitivity: "点击查看药物敏感性分析 →",
      fusionInfoTitle: "融合信息",
      variantStatsTitle: "变体统计概览",
      totalVariants: "总变体数",
      highestFQ: "最高FQ",
      junctionDistTitle: "Junction/Spanning 分布",
      geneNetworkTitle: "基因关系网络",
      upsetTitle: "样本共现融合分析",
      upsetTooltip1: "统计含有该融合的所有样本中，与其他融合基因的共现情况。",
      upsetTooltip2: "纵轴：出现频率前10的共现融合（当前融合始终显示在最下方）。",
      upsetTooltip3: (color) => `顶部柱状图：共现交集的样本数量，<span style={{color:'${color}'}}>紫色</span>为仅含当前融合的样本。`,
      upsetTooltip4: "右侧柱状图：每种融合在全部样本中的出现总数。",
      diagramTitle: "融合断点图",
      recommended: "推荐",
      diagramTooltip1: "基于 Arriba 工具设计并适配 SNIFFER 结果文件。ENST 转录本注释使用 GRCh38 的 GENCODE v36。",
      diagramTooltip2: "Arriba 绘图后端默认使用 GENCODE v36 注释和 GRCh38 protein domains v2.5.1；缺少可用 ENST/CDS 转录本编号的变体可能无法绘制。",
      proView: "专业图",
      interactiveView: "交互图",
      showBoth: "同时显示",
      noVisualizationData: "暂无可视化数据",
      selectRecordHint: "请通过上方图表或图例选择一条记录",
      interactiveDiagramTitle: "交互式融合结构图",
      proteinTitle: "融合蛋白结构预测",
      dataTableTitle: (id) => `详细数据 (当前变体 ID: ${id})`,
      fqValueLabel: "FQ值:",
      exportJSON: "导出JSON",
      selectRecordHint2: "请选择一条记录",
      variantListHeader: (title, n) => `${title} 变体列表 (${n}个)`,
      fusionTypeLabel: "类型:",
      chartNoData: "暂无数据",
      dbAvgJunction: (v) => `全库平均Junction: ${v}`,
      fusionJunctionAvg: (v) => `当前融合Junction均值: ${v}`,
      dbAvgSpanning: (v) => `全库平均Spanning: ${v}`,
      fusionSpanningAvg: (v) => `当前融合Spanning均值: ${v}`,
      networkNoData: "暂无数据",
      forwardFusion: "→ 正向融合",
      reverseFusionLabel: (name) => `↩ 反向融合: ${name}`,
      variantFqInfo: (count, fq) => `变体数: ${count}  FQ: ${fq}`,
      nodeInfo: (id, count, fq) => `${id}: 变体${count}个, FQ=${fq}`,
      clickToJump: "点击跳转详情页",
      legend5prime: "5'端",
      legend3prime: "3'端",
      legendForward: "正向",
      legendReverse: "反向",
      geneBreakpointTitle: "基因与断点信息",
      leftGeneHeader: "5' 端（左侧基因）",
      rightGeneHeader: "3' 端（右侧基因）",
      geneNameLabel: "基因名:",
      ensgLabel: "ENSG:",
      breakpointLabel: "断点:",
      dinucLabel: "Dinuc:",
      entropyLabel: "熵值:",
    },
    arriba: {
      loadingVariants: "正在加载变体数据...",
      envNotReady: "Arriba环境未就绪",
      envCheckConfig: "无法生成融合断点图，请检查以下配置：",
      envConda: (env) => `Conda环境 (${env})`,
      envRScript: "draw_fusions.R脚本",
      envAnnotation: "注释文件 (GTF)",
      envCytobands: "Cytobands文件",
      envProteinDomains: "蛋白结构域文件",
      currentVariantId: "当前所选变体ID:",
      zoomOut: "缩小",
      zoomIn: "放大",
      fullscreen: "全屏查看",
      regenerate: "重新生成",
      downloadPdf: "下载PDF",
      generating: "正在生成Arriba融合图...",
      generatingHint: "这可能需要10-30秒",
      generateFailed: "生成失败",
      retry: "重试",
      selectVariantHint: "选择一个变体查看融合图",
      variantSelectorTitle: "断点变体",
      variantCount: (n) => `共 ${n} 个变体，按FQ值排序`,
      variantLabel: (n) => `变体 ${n}`,
      highestFQ: "最高FQ",
      leftBreakpoint: "左断点:",
      rightBreakpoint: "右断点:",
      currentVariantLabel: "当前:",
      legendTitle: "图例说明",
      legend5prime: "5'端基因 (Gene1)",
      legend3prime: "3'端基因 (Gene2)",
      legendBreakpoint: "融合断点连接",
      legendDomain: "保守蛋白结构域",
      close: "关闭",
    },
    fusionProtein: {
      loading3d: "正在加载3D查看器...",
      styleCartoon: "卡通",
      styleStick: "棍状",
      styleSphere: "球状",
      surfaceOn: "关闭表面",
      surfaceOff: "显示表面",
      surfaceLabel: "表面",
      spinStop: "停止旋转",
      spinStart: "开始旋转",
      resetView: "重置视图",
      footerStructure: (id) => `🧬 T${id} 融合蛋白结构`,
      footerEsmfold: "ESMFold 预测",
      footerSurface: "+ 表面层",
      footerHint: "拖拽旋转 · 滚轮缩放 · 右键平移",
      colorLegendTitle: "颜色图例 (N→C端)",
      colorLegendLabel: "N端 → C端",
      generatingEsmfold: "ESMFold 正在折叠蛋白质结构...",
      noSequence: "未找到蛋白质序列数据",
      noSequenceHint: "fusion_transl 字段为空",
      sectionTitle: "融合蛋白结构预测",
      loadingAlphafold: "正在查询AlphaFold数据库...",
      loadFailed: "加载失败",
      checkingPdb: (id) => `正在检查 T${id} 的PDB文件...`,
      generating3d: (id) => `正在生成 T${id} 的蛋白质3D结构...`,
      cancel: "取消",
      esmfoldProgress: "ESMFold正在折叠蛋白质结构，通常需要1-3分钟...",
      predictionDone: (id) => `🎉 T${id} 融合蛋白结构预测完成！`,
      fromCache: "从缓存加载",
      aaCount: (n) => `${n} 个氨基酸`,
      downloadPdb: (id) => `下载 T${id}.pdb`,
      repredict: "重新预测",
      load3dFailed: "无法加载3D结构",
      refetch: "重新获取",
      autoPredictFailed: (id) => `T${id} 自动预测未能完成`,
      useManualTools: "请使用下方工具手动预测",
      retry: "重试",
      openZjuAF3: "手动前往浙大AF3",
      startPredict: (id) => `开始预测 T${id}`,
      onlinePredictTitle: "⚡ 在线预测融合蛋白3D结构",
      currentVariant: (id) => `当前选中: T${id}`,
      onlinePredictDesc: "选择以下工具预测完整融合蛋白的3D结构（需要在外部网站进行）",
      sequenceLabel: "融合蛋白序列: ",
      filteredChars: (n) => `已过滤 ${n} 个无效字符`,
      overLimit: "超过ESMFold限制",
      copied: "已复制",
      copySequence: "复制序列",
      recommended: "推荐",
      zjuAF3Name: "浙大 AlphaFold3",
      zjuAF3Tagline: "✓ 精度最高 · 国内访问",
      zjuAF3Desc: "浙江大学 AlphaFold3 镜像服务，支持任意长度序列，预测约 5-30 分钟。",
      zjuAF3Access: "✓ 国内网络直连",
      zjuAF3Btn: "复制序列 & 打开网站",
      esmfoldName: "ESMFold",
      esmfoldTagline: "⚡ 速度最快",
      esmfoldDesc: "Meta AI 语言模型预测，适合 <400aa 序列，预测约 1-2 分钟。",
      esmfoldNoLimit: "无次数限制",
      esmfoldBtn: "复制序列 & 打开网站",
      colabfoldName: "ColabFold",
      colabfoldTagline: "🆓 免费",
      colabfoldDesc: "AlphaFold2 的免费在线版本，需要 Google 账号，无次数限制，预测约 10-30 分钟。",
      colabfoldBtn: "复制序列 & 打开网站",
      usageTips: "💡 使用提示:",
      tip1: "点击按钮后，序列会自动复制到剪贴板，同时打开对应网站",
      tip2: "在外部网站粘贴序列 (Ctrl+V) 即可开始预测",
      tip3: "预测完成后可下载 PDB 文件，使用上方3D查看器或 PyMOL 查看",
      singleGeneTitle: "单基因结构",
      dataSource: "数据来源",
      dataSourceValue: "AlphaFold v4",
      fusionGeneLabel: "融合基因",
      seqLengthLabel: "序列长度",
      viewOptionsTitle: "查看选项",
      leftGeneNterm: (g) => `${g} (N端)`,
      rightGeneCterm: (g) => `${g} (C端)`,
      openInAlphafold: (g) => `在AlphaFold中打开 ${g}`,
      waitingStructure: "等待加载结构数据...",
      currentView: (g) => `当前查看: ${g}`,
      confidenceLegend: "置信度图例",
      seqSectionTitle: "融合蛋白氨基酸序列",
      seqOriginalValid: (orig, valid) => `(原始: ${orig} | 有效: ${valid} aa)`,
      hasInvalidChars: "含无效字符",
      copyValidSeq: "复制有效序列",
      copyRawSeq: "复制原始序列",
      copiedAlert: "已复制清理后的序列",
      noValidSeq: "无有效序列",
      errNoAA: "无有效的氨基酸序列",
      errSeqTooLong: (n) => `序列长度 (${n}aa) 超过ESMFold限制 (400aa)，请使用下方外部工具预测`,
      errAutoSeqTooLong: (n) => `序列长度 ${n} aa，超过当前自动预测范围。`,
      errEsmTooLong: (n) => `序列长度 ${n} aa，超过 ESMFold 自动预测范围，因此不进行自动预测。`,
      errEsmFailed: (msg) => msg ? `ESMFold 自动预测失败：${msg}。` : "ESMFold 自动预测失败。",
      errPredictFailed: "预测失败",
      errNoUniProt: "未找到对应的UniProt ID",
      errUniProtQuery: (msg) => `查询UniProt数据库失败: ${msg}`,
      // Local ColabFold / ESMFold preview status
      localAf2Label: "本地 AlphaFold2 / ColabFold",
      localColabfoldRunningText: "本地 ColabFold 正在折叠蛋白质结构...",
      localColabfoldProgressText: "本地 AlphaFold2 / ColabFold 正在本地预测。首次运行可能较慢，因为正在准备模型参数、JAX 编译或 GPU 初始化。",
      esmPreviewLabel: "ESMFold · 快速预览",
      esmPreviewLoadingTitle: "⚡ ESMFold 快速预览加载中...",
      esmPreviewLoadingDesc: "正在通过 ESMFold 获取快速结构预览，同时后台已启动本地 ColabFold 进行最终预测。",
      esmPreviewTitle: "ESMFold 快速预览",
      esmPreviewNotFinal: "临时预览结构，不是最终结构",
      esmPreviewRunningBanner: "ESMFold 快速预览已加载，本地 ColabFold 正在后台预测，完成后将自动覆盖...",
      esmPreviewErrorBanner: "本地 ColabFold 后台预测失败，当前显示 ESMFold 快速预览结果。",
      retryColabFold: "重试 ColabFold",
      esmPreviewOverwritten: "已覆盖 ESMFold 快速预览",
      colabfoldStartFailed: "ColabFold 启动失败",
      colabfoldNoJobId: "ColabFold 未返回 job_id",
      colabfoldTimeoutPreview: "本地 AlphaFold2 / ColabFold 预测超时，当前保留 ESMFold 快速预览结果。",
      colabfoldTimeoutError: "本地 AlphaFold2 / ColabFold 轮询后仍超时，请检查后端日志或稍后重试。",
      alertNoSeq: "没有有效的氨基酸序列",
      alertCopiedZju: (n) => `序列已复制！(${n}aa)\n\n在浙大AlphaFold3网站:\n1. 粘贴到 "🧬 蛋白质序列"\n2. 点击 "🚀 运行 AlphaFold 3"`,
      alertCopiedEsm: (n) => `序列已复制！(${n}aa)\n\n在ESMFold网站粘贴序列进行预测`,
      alertCopiedColab: (n) => `序列已复制！(${n}aa)\n\nColabFold Notebook中粘贴序列`,
      alertCopyFailed: "复制失败，请手动复制",
    },
    transcriptome: {
      pageTitle: "转录组分析",
      exportData: "导出数据",
      tabExpression: "基因表达量比较",
      tabDifferential: "差异表达分析",
      tabEnrichment: "GO/KEGG富集分析",
      noData: "暂无数据",
      noExpressionData: "无表达数据",
      expressionSectionTitle: "基因表达量比较图",
      expressionSectionDesc: "比较融合阳性(+)和融合阴性(-)样本中融合基因的表达水平差异。数据来源: normalized.all.count (TPM)",
      fusionPositiveSamples: "融合阳性样本",
      fusionNegativeSamples: "融合阴性样本",
      avgFFPM: "平均FFPM",
      fusionType: "融合类型",
      fusionPositiveLabel: "融合阳性 (+)",
      fusionNegativeLabel: "融合阴性 (-)",
      nMeanStd: (n, mean, std) => `n = ${n} | 均值 = ${mean} ± ${std}`,
      loadingExpression: "加载转录组分析数据...",
      loadingDiff: "正在进行DESeq2差异表达分析...",
      loadingDiffHint: "使用count数据进行分析，这可能需要一些时间",
      loadingEnrich: "正在进行富集分析...",
      loadingEnrichHint: "正在运行本地 R/clusterProfiler 分析...",
      diffMethodTitle: "分析方法",
      method: "方法",
      log2fcThreshold: "log2FC阈值",
      fdrThreshold: "FDR阈值",
      dataSource: "数据来源",
      diffSummaryTitle: "差异基因统计",
      genesDetected: "检测基因",
      upRegulated: "上调基因",
      downRegulated: "下调基因",
      volcanoTitle: "差异表达火山图 (DESeq2)",
      up: "上调",
      down: "下调",
      ns: "不显著",
      exportPDF: "导出PDF",
      degTableTitle: "差异表达基因 (Top 100)",
      upLabel: (n) => `上调 (${n})`,
      downLabel: (n) => `下调 (${n})`,
      export: "导出",
      colGene: "基因",
      colLog2FC: "log2FC",
      colPValue: "P值",
      colFDR: "FDR",
      colBaseMean: "Base Mean",
      showingGenes: (start, end, total) => `显示 ${start}-${end} / 共 ${total} 个基因`,
      noDataDiff: "无法加载差异分析数据",
      noDataEnrich: "无法加载富集分析数据",
      enrichBanner: "富集分析基于差异表达基因",
      enrichBannerDesc: "已将显著差异基因合并后统一进行 GO/KEGG 富集分析，不再拆分 Up/Down 分别分析。",
      enrichPlotNote: "图形由后端 R/clusterProfiler 生成；PNG 用于网页预览，PDF 可直接下载。",
      combinedDEG: "合并差异基因",
      sourceLabel: "来源",
      mappedGenes: "映射基因数",
      generatedPlot: "R/clusterProfiler 生成图形",
      noEnrichmentPlot: "没有显著条目或未生成 R 图形",
      noEnrichmentResult: "暂无富集分析结果",
      noEnrichmentReason: "当没有条目通过校正后 P 值阈值时会出现这种情况。",
      goBpTitle: "GO 生物过程",
      goMfTitle: "GO 分子功能",
      goCcTitle: "GO 细胞组分",
      keggTitle: "KEGG 通路",
      termId: "条目 ID",
      geneCount: "基因数",
      geneRatio: "基因比例",
      adjustedP: "校正后 P 值",
      genesLabel: "基因",
      upGenesCount: (n) => `上调基因: ${n} 个`,
      downGenesCount: (n) => `下调基因: ${n} 个`,
      enrichTooltipHint: "💡 鼠标悬停在通路名称或气泡上可查看完整信息",
      upEnrichTitle: "上调基因富集分析",
      downEnrichTitle: "下调基因富集分析",
      noSigDEG: "未发现显著差异表达基因",
      noDotPlotData: (title) => `暂无${title}富集结果`,
      exportPdfFailed: "导出失败：找不到图表元素",
      exportPdfInstall: "PDF导出失败，请确保已安装 html2canvas 和 jspdf",
    },
    clinical: {
      loading: "正在加载临床数据分析...",
      loadingFusionLabel: "融合基因:",
      unavailableTitle: "临床数据不可用",
      unavailableFusion: "融合基因:",
      unavailablePositive: "阳性样本:",
      unavailableNegative: "阴性样本:",
      unavailableLifelines: (v) => `lifelines可用: ${v ? '是' : '否'}`,
      backToDetail: "返回详情页",
      backToFusionDetail: "返回融合详情",
      os: "总生存期 (OS)",
      efs: "无事件生存期 (EFS)",
      exportReport: "导出报告",
      pageTitle: "临床数据分析",
      totalSamples: "总样本:",
      fusionPositive: "融合阳性:",
      totalEvents: "事件数:",
      retrying: "重试",
      switchingType: "正在切换分析类型...",
      kmTitle: (label) => label,
      noKmData: "暂无生存曲线数据",
      tooltipTime: "时间:",
      tooltipTimeUnit: "年",
      tooltipAtRisk: (pos, neg) => `风险集: 阳性 ${pos} / 阴性 ${neg}`,
      followupTime: "随访时间 (年)",
      survivalProb: "生存概率",
      fusionPositiveLabel: "融合阳性",
      fusionNegativeLabel: "融合阴性",
      positiveGroup: "融合阳性组",
      negativeGroup: "融合阴性组",
      sampleN: "样本数:",
      events: "事件数:",
      medianSurvival: "中位生存:",
      medianNotReached: "未达到",
      survivalYears: "年",
      survival5y: "5年生存率:",
      coxError: (msg) => msg || "Cox回归分析失败",
      coxTitle: "Cox多因素回归分析",
      coxModel: "模型: Surv(time, event) ~ fusion_status + age + sex + risk_group",
      cIndex: "一致性指数:",
      sampleSize: "样本量:",
      eventCount: "事件数:",
      colVariable: "变量",
      colPValue: "P值",
      colSignificance: "显著性",
      significant: "✓ 显著",
      notSignificant: "不显著",
      hrExplain: "HR（风险比）：HR > 1 表示风险较高，HR < 1 表示风险较低。",
      forestTitle: "HR",
      forestLoadingRef: "加载参考融合数据...",
      forestCurrentFusion: "当前融合",
      forestOncogenicRef: "High risk Fusion",
      forestFavorableRef: "Low risk Fusion",
      forestOncogenicLabel: "致癌融合 (Oncogenic)",
      forestFavorableLabel: "抑癌融合 (Tumor Suppressor)",
      forestNote: "HR（风险比）用于比较两组事件发生风险；HR > 1 表示风险较高，HR < 1 表示风险较低。",
      osUnavailable: "总生存期 (OS) 数据不可用",
      efsUnavailable: "无事件生存期 (EFS) 数据不可用",
      forestWarningText: "⚠ 此 HR 估计不可靠：阳性组事件（死亡/复发）极少，导致 Cox 回归出现准完全分离，系数估计发散。请以上方 KM 生存曲线作为预后评估依据。",
      favorablePrognosis: "有利预后",
      unfavorablePrognosis: "不利预后",
      clinicalSummaryTitle: "临床特征摘要",
      patientsCount: (n) => `(${n} 例患者)`,
      demographicsTitle: "人口学特征",
      genderDist: "性别分布",
      diagnosisAge: "诊断年龄 (年)",
      median: "中位数:",
      fabClassification: "FAB分型",
      riskStratTitle: "风险分层",
      outcomesTitle: "预后结局",
      survivalStatus: "生存状态",
      overallSurvivalTime: "总生存时间",
      medianYears: (v) => `中位数: ${v} 年`,
      analysisNotesTitle: "分析说明",
      kmNote: "比较融合阳性和融合阴性患者的生存差异，使用 Log-rank 检验评估统计学显著性。",
      coxNote: "Cox多因素回归: 在控制年龄、性别、风险分组等混杂因素后，评估融合基因状态对生存的独立影响。HR < 1 表示该融合基因与更好的预后相关，HR > 1 表示与更差的预后相关。",
      timeNote: "注意: 时间单位已转换为年（原始数据为天/365）。p < 0.05 被认为具有统计学显著性。",
    },
    sniffer: {
      loginRequired: "SNIFFER 需要登录",
      loginDesc: "请登录后使用 SNIFFER 融合基因检测算法进行分析",
      loginBtn: "点击登录",
      loggedInAs: (u) => `已登录: ${u}`,
      analyzing: "请勿关闭页面，分析完成后将自动显示结果",
      noData: "暂无数据",
      noDataHint: "请上传 CSV 或 XLSX 文件",
      analysisComplete: "分析完成",
      snifferResults: "SNIFFER 检测结果",
      fusionRecords: "融合记录",
      uniqueFusions: "独立融合",
      genesInvolved: "涉及基因",
      chromosomes: "染色体",
      topFusionsTitle: "检测到的融合基因 (Top 10)",
      downloadResults: "下载结果",
      newAnalysis: "新分析",
      panelTitle: "SNIFFER 分析",
      tabTsv: "TSV 融合结果",
      tabFastq: "FASTQ 完整分析",
      tsvModeTitle: "TSV 模式",
      tsvModeDesc: (e1, e2) => `上传 StarFusion/Arriba 等工具的融合结果文件，使用 SNIFFER 进行${e1}和${e2}。`,
      tsvModeE1: "融合相似性筛选",
      tsvModeE2: "准确性打分",
      fastqModeTitle: "FASTQ 模式",
      fastqModeDesc: (e1) => `上传配对的 FASTQ 测序文件，完整运行 SNIFFER 流程检测融合基因。支持${e1}`,
      fastqModeE1: "配对末端测序",
      dropHint: "拖拽文件到此处",
      dropHint2: "或点击下方选择文件",
      fusionFileLabel: "融合结果文件 (TSV/CSV/TXT)",
      read1Label: "Read 1 (正向)",
      read2Label: "Read 2 (反向)",
      uploading: "正在上传文件...",
      uploadingBtn: "上传中...",
      startAnalysis: "开始分析",
      reset: "重置",
      usageTitle: "使用说明",
      tsvStep1: "1. 上传融合检测结果文件（StarFusion/Arriba 输出）",
      tsvStep2: "2. SNIFFER 将进行序列相似性分析和融合打分",
      tsvStep3: "3. 下载带有置信度评分的结果文件",
      fastqStep1: "1. 上传配对的 FASTQ 文件（Read 1 和 Read 2）",
      fastqStep2: "2. 点击「开始分析」启动 SNIFFER 检测流程",
      fastqStep3: "3. 等待分析完成，下载融合基因检测报告",
      fqPanelTitle: "Fusion FQ 柱状图",
      clearData: "清除数据",
      fqDesc1: "上传包含",
      fqDesc2: "和",
      fqDesc3: "列的 CSV 文件",
      fqUploadHint: "点击上传 FQ 数据文件",
      fqUploadHint2: "支持 CSV、XLSX 格式",
      fqRecords: (n) => `${n.toLocaleString()} 条记录`,
      showLabel: "显示:",
      chartNote1: "• 灰色条表示 FFPM ≥ 0.1 的融合（高表达）",
      chartNote2: "• 红色条表示 FFPM < 0.1 的融合（低表达，可能为假阳性）",
      chartNote3: "• 斜体标签表示该融合仅有低表达记录",
      analyzingMsg: (msg) => msg || "正在分析...",
      errLoginExpired: "登录已过期，请重新登录",
      errUploadFailed: "上传失败",
      errUploadRetry: "上传失败，请重试",
      errNetwork: "网络错误，请检查连接",
      errDownload: "下载失败",
      errCsvOnly: "请上传 CSV 格式文件",
      errParseFailed: (msg) => `文件解析失败: ${msg}`,
      taskResuming: "恢复任务中...",
      taskStarting: "任务启动中...",
    },
    chromosomeDetail: {
      loading: (chr) => `正在加载 ${chr} 染色体数据...`,
      loadFailTitle: "加载失败",
      backToHome: "返回首页",
      chrTitle: (chr) => `${chr} 染色体`,
      chrNameLabel: "染色体名称",
      totalFusions: "融合基因总数",
      genesInvolved: "涉及基因数",
      searchPlaceholder: "搜索基因名、融合名、样本名...",
      searchBtn: "搜索",
      clearBtn: "清除",
      fusionListTitle: "融合基因列表",
      searchLabel: (q) => `(搜索: "${q}")`,
      sortFieldFq: "频率",
      sortFieldFfpm: "Avg FFPM",
      sortDesc: "降序",
      sortAsc: "升序",
      sortInfo: (fieldLabel, orderLabel) => `按${fieldLabel}${orderLabel}排列`,
      loadingMore: "加载中...",
      noData: "暂无数据",
      noDataHint: "该染色体上没有找到融合基因",
      colFusionName: "融合名称",
      colLeftGene: "左侧基因",
      colLeftBreakpoint: "左侧断点",
      colRightGene: "右侧基因",
      colRightBreakpoint: "右侧断点",
      colChrBand: "染色体带",
      colAnnots: "注释",
      colFrequency: "频率",
      showingRange: (start, end, total) => `显示第 ${start} - ${end} 条，共 ${total} 条`,
      firstPage: "首页",
      lastPage: "末页",
      goToPage: "跳转到",
      pageInfo: (totalPages) => `页 / 共 ${totalPages} 页`,
      fetchError: "获取染色体数据失败",
    },
    geneFunction: {
      loading: (gene) => `正在查询 ${gene} 基因信息...`,
      notFound: "未找到基因信息",
      queryFailed: "查询失败",
      title: (gene) => `${gene} 基因功能`,
      fullName: "全名：",
      type: "类型：",
      summary: "摘要：",
      alias: "别名：",
    },
    fusionDeletedDetail: {
      loading: "正在加载...",
      loadFailTitle: "加载失败",
      notFoundData: "未找到数据",
      backBtn: "返回",
      variantsCount: (n) => `${n} 个变体`,
      filterReasonTitle: "⚠️ 被列为低可信度的原因",
      filterReasonHint: "该融合基因未通过 SNIFFER 质量筛选，结果仅供参考",
      variantCount: "变体数",
      totalFq: "总 fq",
      variantListTitle: (n) => `📋 变体列表（${n} 个，按 fq 排序，点击查看详情）`,
      tableHeaders: ['编号', 'Left Breakpoint', 'Right Breakpoint', 'fq', 'Junction', 'Spanning', '蛋白类型', 'Filter'],
      geneBreakpointTitle: "基因与断点信息",
      leftGeneHeader: "5' 端（左侧基因）",
      rightGeneHeader: "3' 端（右侧基因）",
      geneNameLabel: "基因名:",
      ensgLabel: "ENSG:",
      breakpointLabel: "断点:",
      dinucLabel: "Dinuc:",
      entropyLabel: "熵值:",
      annotLabel: "注释：",
      spliceTypeLabel: "剪切类型:",
      largeAnchorLabel: "大锚支持:",
      protFusionTypeLabel: "蛋白融合类型:",
      arribaTitle: "融合断点图（Arriba）",
      arribaRecommended: "推荐",
      dataTableTitle: (id) => `详细数据（TF${id || 'N/A'}）`,
      exportJSON: "导出JSON",
      selectRecordHint: "请选择一条记录",
      paginationRange: (start, end, total) => `第 ${start}-${end} 条 / 共 ${total} 条`,
    },
    cellLineDetail: {
      viewTargetData: "查看 Target 数据",
      geneInfoTitle: "基因信息",
      geneBreakpointTitle: "基因与断点信息",
      leftGeneHeader: "5' 端（左侧基因）",
      rightGeneHeader: "3' 端（右侧基因）",
      geneNameLabel: "基因名:",
      ensgLabel: "ENSG:",
      breakpointLabel: "断点:",
      dinucLabel: "Dinuc:",
      fusionNameLabel: "融合名称",
      leftGeneLabel: "左侧基因",
      rightGeneLabel: "右侧基因",
      functionLeftLabel: "左侧功能",
      functionRightLabel: "右侧功能",
      cdsLeftLabel: "左侧 CDS 状态",
      cdsRightLabel: "右侧 CDS 状态",
      avgFfpmLabel: "Avg FFPM",
      totalFqLabel: "总频次",
    },
    drugSensitivity: {
      pageTitle: "药物敏感性分析",
      dataSourceLabel: "数据来源：",
      dataSourceGDSC: "(Genomics of Drug Sensitivity in Cancer) 细胞系药物敏感性",
      backToDetail: "返回详情页",
      disclaimer: "免责声明",
      disclaimerText: "本页面展示的 GDSC 细胞系药物敏感性数据来源于 Genomics of Drug Sensitivity in Cancer (GDSC) 项目。基因表达与药物敏感性的相关性分析仅反映细胞系层面的统计关联，不代表临床层面的因果关系。本页信息仅供科研参考，不构成临床诊疗建议。",
      cannotParseGene: "无法从融合名称解析基因",
      expectedFormat: "预期格式: GENE1--GENE2",
      githubLabel: "GitHub 项目：",
    },
    drugGeneSearch: {
      pageTitle: "药物-基因敏感性分析",
      pageSubtitlePrefix: "基于 ",
      pageSubtitleSuffix: " · 输入基因或融合基因名称，探索癌症细胞系中的药物敏感性",
      searchBoxTitle: "搜索基因 / 融合基因",
      searchHint: "单基因：",
      searchHintFusion: "融合：",
      placeholder: "输入基因名或融合名，例如 RUNX1--RUNX1T1",
      recentSearches: "最近搜索",
      analyze: "分析",
      examples: "示例：",
      fusionFormatTitle: "融合基因格式",
      fusionFormatDesc: "支持融合基因 / 单基因分析模式",
      geneFormatTitle: "单基因格式",
      geneFormatDesc: "基因表达分析模式",
      resultsFor: "当前分析：",
      fusionBadge: "融合",
      geneBadge: "基因",
      clear: "清除",
      emptyTitle: "输入基因或融合名称开始分析",
      emptySubtitle: "结果将显示在此处",
      disclaimerTitle: "免责声明",
      disclaimerText: "本页面展示的 GDSC 细胞系药物敏感性数据来源于 Genomics of Drug Sensitivity in Cancer (GDSC) 项目。基因表达与药物敏感性的相关性分析仅反映细胞系层面的统计关联，不代表临床层面的因果关系。本页信息仅供科研参考，不构成临床诊疗建议。",
      invalidInput: "请输入有效的基因名（如 RUNX1）或融合名（如 RUNX1--RUNX1T1）",
      githubLabel: "GitHub 项目：",
    },
    gdsc: {
      title: "GDSC 细胞系药物敏感性分析",
      dataSource: "数据来源：",
      dataSourceSuffix: "(Genomics of Drug Sensitivity in Cancer)",
      analyzeGene: "分析基因：",
      analyzeFusion: "分析融合",
      fusionPositive: "融合阳性",
      fusionNegative: "融合阴性",
      highExpression: "高表达组",
      lowExpression: "低表达组",
      metricZScore: "Z_SCORE (Z分数)",
      metricLnIc50: "LN_IC50",
      metricAuc: "AUC",
      metricRmse: "RMSE",
      descZScore: "Z分数：衡量药物敏感性相对于平均水平的标准化得分。正值表示比平均水平更耐药，负值表示比平均水平更敏感。",
      descLnIc50: "LN_IC50：IC50 的自然对数值，表示抑制 50% 细胞生长所需的药物浓度。值越大越耐药。",
      descAuc: "AUC：剂量-反应曲线下面积，值越大表示越耐药。",
      descRmse: "RMSE：剂量-反应模型的拟合误差。",
      splitMedian: "中位数",
      splitUpperTertile: "上三分位",
      splitLowerTertile: "下三分位",
      splitUpperQuartile: "上四分位",
      splitLowerQuartile: "下四分位",
      metricLabel: "指标：",
      groupLabel: "分组：",
      sortLabel: "排序：",
      sortSuffix: "排序",
      noSort: "不排序",
      reset: "重置",
      fusionGroupMode: "融合分组模式",
      fusionGroupDesc: (name) => `根据细胞系是否携带 `,
      fusionGroupDescBold: (name) => name,
      fusionGroupDescMid: " 融合，分为",
      fusionGroupDescPos: (n) => ` 融合阳性（${n} 个）`,
      fusionGroupDescAnd: "和",
      fusionGroupDescNeg: (n) => ` 融合阴性（${n} 个）`,
      fusionGroupDescEnd: "两组。",
      positiveCellLines: "阳性细胞系：",
      fusionNotDetectedCCLE: "该融合在 CCLE 细胞系中未检测出，请查看相关基因的药物敏感性。",
      dataNotConfigured: "GDSC 数据未配置",
      dataNotConfiguredDesc1: "请将 ",
      dataNotConfiguredDesc2: " 和 ",
      dataNotConfiguredDesc3: " 放到后端 ",
      dataNotConfiguredDesc4: " 目录下",
      loadingData: (gene) => `正在加载 ${gene} 的 GDSC 数据...`,
      geneNotFound: (gene) => `基因 ${gene} 在 GDSC 数据库中未找到`,
      totalSamples: "样本总数",
      drugCount: "药物数量",
      fusionScatterTitle: (name) => `${name} 融合分组下的药物敏感性散点图`,
      geneScatterTitle: (gene) => `${gene} 表达水平（FPKM）分组下的药物敏感性散点图`,
      noDrugData: "暂无药物数据",
      drugDetails: "药物详情",
      clickDrugDot: "点击散点图中的药物点查看",
      drugDetailInfo: "药物详细信息",
      drugName: "药物名称",
      target: "靶点",
      pathway: "通路",
      meanLabel: "均值",
      meanSdLabel: "均值 ± SD",
      diffPValue: "差异 p 值",
      sigDiffMsg: (labelA, labelB, metric) => `✓ 该药物在 ${labelA}/${labelB} 间的 ${metric} 存在显著差异 (p < 0.05)`,
      noSigDiffMsg: (labelA, labelB, metric) => `药物在 ${labelA}/${labelB} 间的 ${metric} 无显著差异 (p ≥ 0.05)`,
      clickDrugDotView: "点击散点图中的药物点",
      viewDrugInfo: "查看药物详细信息",
      drugAnalysisTitle: (name) => `药物 "${name}" 详细分析`,
      switchDrugHint: "点击散点图中的其他药物点可切换",
      correlationMetricLabel: "相关性指标：",
      correlationTitle: (gene, drug, metric) => `${gene} 表达值 vs ${drug} ${metric} 相关性`,
      corrCoeff: "相关系数 (r):",
      pValue: "P值:",
      sampleCountN: "样本数 (n):",
      significance: "显著性:",
      significant: "(显著)",
      notSignificant: "(不显著)",
      insufficientData: "数据不足",
      drugGroupDistTitle: (drug, labelA, labelB, metric) => `"${drug}" 在 ${labelA}/${labelB} 中的 ${metric} 分布`,
      samplesStat: (label, n) => `${label}: ${n} 样本`,
      expressionDistTitle: (gene) => `${gene} 表达值分布`,
      expressionAxisLabel: "表达值 (FPKM)",
      otherCategory: "其他",
      groupHistology: "疾病类型",
      groupSite: "组织部位",
      clickForAnalysis: "点击散点图中的药物点查看详细分析",
      analysisIncludes: "包含相关性分析、高低组分布对比和药物详情",
      fusionStatsLine: (name, labelA, highN, labelB, lowN, metric) => `融合: ${name}；${labelA}: ${highN}；${labelB}: ${lowN}；指标: ${metric}`,
      geneStatsLine: (gene, total, labelA, highN, labelB, lowN, metric, split) => `基因: ${gene}；样本总数: ${total}；${labelA}: ${highN}；${labelB}: ${lowN}；指标: ${metric}；分组: ${split}`,
    },
  }
};

const LanguageContext = createContext({ language: 'en', setLanguage: () => {} });

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('language');
    if (savedLang && (savedLang === 'en' || savedLang === 'zh')) setLanguage(savedLang);
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => React.useContext(LanguageContext);
